# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Editor.ui'
#
# Created: Thu Mar 15 23:32:01 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Editor(object):
    def setupUi(self, Editor):
        Editor.setObjectName(_fromUtf8("Editor"))
        Editor.resize(821, 755)
        Editor.setAnimated(True)
        self.centralwidget = QtGui.QWidget(Editor)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.widget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(150, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(230, 16777215))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.FilesList = QtGui.QListWidget(self.groupBox_2)
        self.FilesList.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.FilesList.setObjectName(_fromUtf8("FilesList"))
        self.verticalLayout_8.addWidget(self.FilesList)
        self.NewConfigButton = QtGui.QPushButton(self.groupBox_2)
        self.NewConfigButton.setObjectName(_fromUtf8("NewConfigButton"))
        self.verticalLayout_8.addWidget(self.NewConfigButton)
        self.ItemsList = QtGui.QListWidget(self.groupBox_2)
        self.ItemsList.setObjectName(_fromUtf8("ItemsList"))
        self.verticalLayout_8.addWidget(self.ItemsList)
        self.NewEntryButton = QtGui.QPushButton(self.groupBox_2)
        self.NewEntryButton.setObjectName(_fromUtf8("NewEntryButton"))
        self.verticalLayout_8.addWidget(self.NewEntryButton)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.MainTabs = QtGui.QTabWidget(self.widget)
        self.MainTabs.setObjectName(_fromUtf8("MainTabs"))
        self.SpriteTab = QtGui.QWidget()
        self.SpriteTab.setObjectName(_fromUtf8("SpriteTab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.SpriteTab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.SpritesMainBox = QtGui.QGroupBox(self.SpriteTab)
        self.SpritesMainBox.setMinimumSize(QtCore.QSize(310, 0))
        self.SpritesMainBox.setMaximumSize(QtCore.QSize(310, 16777215))
        self.SpritesMainBox.setObjectName(_fromUtf8("SpritesMainBox"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.SpritesMainBox)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.ID_6 = YReadOnlySimpleInputWidget(self.SpritesMainBox)
        self.ID_6.setEnabled(True)
        self.ID_6.setObjectName(_fromUtf8("ID_6"))
        self.verticalLayout_16.addWidget(self.ID_6)
        self.Name_4 = YSimpleInputWidget(self.SpritesMainBox)
        self.Name_4.setEnabled(True)
        self.Name_4.setObjectName(_fromUtf8("Name_4"))
        self.verticalLayout_16.addWidget(self.Name_4)
        self.Type_3 = YComboBoxWidget(self.SpritesMainBox)
        self.Type_3.setEnabled(True)
        self.Type_3.setObjectName(_fromUtf8("Type_3"))
        self.verticalLayout_16.addWidget(self.Type_3)
        self.Image_5 = YFileInputWidget(self.SpritesMainBox)
        self.Image_5.setObjectName(_fromUtf8("Image_5"))
        self.verticalLayout_16.addWidget(self.Image_5)
        self.Width_2 = YSpinBoxInputWidget(self.SpritesMainBox)
        self.Width_2.setObjectName(_fromUtf8("Width_2"))
        self.verticalLayout_16.addWidget(self.Width_2)
        self.Height_2 = YSpinBoxInputWidget(self.SpritesMainBox)
        self.Height_2.setObjectName(_fromUtf8("Height_2"))
        self.verticalLayout_16.addWidget(self.Height_2)
        self.OffsetX = YSpinBoxInputWidget(self.SpritesMainBox)
        self.OffsetX.setObjectName(_fromUtf8("OffsetX"))
        self.verticalLayout_16.addWidget(self.OffsetX)
        self.OffsetY = YSpinBoxInputWidget(self.SpritesMainBox)
        self.OffsetY.setObjectName(_fromUtf8("OffsetY"))
        self.verticalLayout_16.addWidget(self.OffsetY)
        self.Rows = YSpinBoxInputWidget(self.SpritesMainBox)
        self.Rows.setObjectName(_fromUtf8("Rows"))
        self.verticalLayout_16.addWidget(self.Rows)
        self.Columns = YSpinBoxInputWidget(self.SpritesMainBox)
        self.Columns.setObjectName(_fromUtf8("Columns"))
        self.verticalLayout_16.addWidget(self.Columns)
        spacerItem = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem)
        self.gridLayout_3.addWidget(self.SpritesMainBox, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        self.groupBox_9 = QtGui.QGroupBox(self.SpriteTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.SpriteImageViewer = YImageViewWidget(self.groupBox_9)
        self.SpriteImageViewer.setStyleSheet(_fromUtf8("background: transparent;"))
        self.SpriteImageViewer.setObjectName(_fromUtf8("SpriteImageViewer"))
        self.horizontalLayout_7.addWidget(self.SpriteImageViewer)
        self.gridLayout_3.addWidget(self.groupBox_9, 0, 1, 1, 1)
        self.MainTabs.addTab(self.SpriteTab, _fromUtf8(""))
        self.EntityTab = QtGui.QWidget()
        self.EntityTab.setObjectName(_fromUtf8("EntityTab"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.EntityTab)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.EntityMainBox = QtGui.QGroupBox(self.EntityTab)
        self.EntityMainBox.setMinimumSize(QtCore.QSize(300, 0))
        self.EntityMainBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.EntityMainBox.setObjectName(_fromUtf8("EntityMainBox"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.EntityMainBox)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.ID = YReadOnlySimpleInputWidget(self.EntityMainBox)
        self.ID.setEnabled(True)
        self.ID.setObjectName(_fromUtf8("ID"))
        self.verticalLayout_7.addWidget(self.ID)
        self.Name = YSimpleInputWidget(self.EntityMainBox)
        self.Name.setEnabled(True)
        self.Name.setObjectName(_fromUtf8("Name"))
        self.verticalLayout_7.addWidget(self.Name)
        self.Type = YComboBoxWidget(self.EntityMainBox)
        self.Type.setEnabled(True)
        self.Type.setObjectName(_fromUtf8("Type"))
        self.verticalLayout_7.addWidget(self.Type)
        self.Image_3 = YImageChooser(self.EntityMainBox)
        self.Image_3.setObjectName(_fromUtf8("Image_3"))
        self.verticalLayout_7.addWidget(self.Image_3)
        self.Picture = YComboBoxWidget(self.EntityMainBox)
        self.Picture.setEnabled(True)
        self.Picture.setObjectName(_fromUtf8("Picture"))
        self.verticalLayout_7.addWidget(self.Picture)
        self.Height = YSpinBoxInputWidget(self.EntityMainBox)
        self.Height.setObjectName(_fromUtf8("Height"))
        self.verticalLayout_7.addWidget(self.Height)
        self.Width = YSpinBoxInputWidget(self.EntityMainBox)
        self.Width.setObjectName(_fromUtf8("Width"))
        self.verticalLayout_7.addWidget(self.Width)
        self.verticalLayout_10.addWidget(self.EntityMainBox)
        self.EntityEntityBox = QtGui.QGroupBox(self.EntityTab)
        self.EntityEntityBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.EntityEntityBox.setObjectName(_fromUtf8("EntityEntityBox"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.EntityEntityBox)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.Damage = YDoubleSpinBoxInputWidget(self.EntityEntityBox)
        self.Damage.setObjectName(_fromUtf8("Damage"))
        self.verticalLayout_12.addWidget(self.Damage)
        self.Speed = YDoubleSpinBoxInputWidget(self.EntityEntityBox)
        self.Speed.setObjectName(_fromUtf8("Speed"))
        self.verticalLayout_12.addWidget(self.Speed)
        self.Bloodcolor = YColorInputWidget(self.EntityEntityBox)
        self.Bloodcolor.setObjectName(_fromUtf8("Bloodcolor"))
        self.verticalLayout_12.addWidget(self.Bloodcolor)
        self.verticalLayout_10.addWidget(self.EntityEntityBox)
        self.EntityFeedBox = QtGui.QGroupBox(self.EntityTab)
        self.EntityFeedBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.EntityFeedBox.setObjectName(_fromUtf8("EntityFeedBox"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.EntityFeedBox)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.Nutritive = YDoubleSpinBoxInputWidget(self.EntityFeedBox)
        self.Nutritive.setObjectName(_fromUtf8("Nutritive"))
        self.verticalLayout_11.addWidget(self.Nutritive)
        self.verticalLayout_10.addWidget(self.EntityFeedBox)
        self.EntityMiscBox = QtGui.QGroupBox(self.EntityTab)
        self.EntityMiscBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.EntityMiscBox.setObjectName(_fromUtf8("EntityMiscBox"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.EntityMiscBox)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.Hp = YDoubleSpinBoxInputWidget(self.EntityMiscBox)
        self.Hp.setObjectName(_fromUtf8("Hp"))
        self.verticalLayout_13.addWidget(self.Hp)
        self.Meeting = YDoubleSpinBoxInputWidget(self.EntityMiscBox)
        self.Meeting.setObjectName(_fromUtf8("Meeting"))
        self.verticalLayout_13.addWidget(self.Meeting)
        self.verticalLayout_10.addWidget(self.EntityMiscBox)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.EntityAnimationBox = QtGui.QGroupBox(self.EntityTab)
        self.EntityAnimationBox.setObjectName(_fromUtf8("EntityAnimationBox"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.EntityAnimationBox)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.Animation = YTableWidget(self.EntityAnimationBox)
        self.Animation.setObjectName(_fromUtf8("Animation"))
        self.verticalLayout_9.addWidget(self.Animation)
        self.verticalLayout_14.addWidget(self.EntityAnimationBox)
        self.EntityAnimaptionPreview = QtGui.QGroupBox(self.EntityTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EntityAnimaptionPreview.sizePolicy().hasHeightForWidth())
        self.EntityAnimaptionPreview.setSizePolicy(sizePolicy)
        self.EntityAnimaptionPreview.setObjectName(_fromUtf8("EntityAnimaptionPreview"))
        self.gridLayout_2 = QtGui.QGridLayout(self.EntityAnimaptionPreview)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.EntityAnimationSettings = YAnimationPreviewWidget(self.EntityAnimaptionPreview)
        self.EntityAnimationSettings.setObjectName(_fromUtf8("EntityAnimationSettings"))
        self.gridLayout_2.addWidget(self.EntityAnimationSettings, 0, 0, 1, 1)
        self.verticalLayout_14.addWidget(self.EntityAnimaptionPreview)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_14)
        self.MainTabs.addTab(self.EntityTab, _fromUtf8(""))
        self.WidgetsTab = QtGui.QWidget()
        self.WidgetsTab.setObjectName(_fromUtf8("WidgetsTab"))
        self.MainTabs.addTab(self.WidgetsTab, _fromUtf8(""))
        self.MapTilesTab = QtGui.QWidget()
        self.MapTilesTab.setObjectName(_fromUtf8("MapTilesTab"))
        self.formLayout_2 = QtGui.QFormLayout(self.MapTilesTab)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.TilesMainBox = QtGui.QGroupBox(self.MapTilesTab)
        self.TilesMainBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.TilesMainBox.setObjectName(_fromUtf8("TilesMainBox"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.TilesMainBox)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.ID_4 = YReadOnlySpinBoxInputWidget(self.TilesMainBox)
        self.ID_4.setEnabled(True)
        self.ID_4.setObjectName(_fromUtf8("ID_4"))
        self.verticalLayout_15.addWidget(self.ID_4)
        self.Name_2 = YSimpleInputWidget(self.TilesMainBox)
        self.Name_2.setObjectName(_fromUtf8("Name_2"))
        self.verticalLayout_15.addWidget(self.Name_2)
        self.Type_4 = YComboBoxWidget(self.TilesMainBox)
        self.Type_4.setEnabled(True)
        self.Type_4.setObjectName(_fromUtf8("Type_4"))
        self.verticalLayout_15.addWidget(self.Type_4)
        self.Image = YImageChooser(self.TilesMainBox)
        self.Image.setObjectName(_fromUtf8("Image"))
        self.verticalLayout_15.addWidget(self.Image)
        self.Picture_2 = YComboBoxWidget(self.TilesMainBox)
        self.Picture_2.setEnabled(True)
        self.Picture_2.setObjectName(_fromUtf8("Picture_2"))
        self.verticalLayout_15.addWidget(self.Picture_2)
        self.Passability = QtGui.QWidget(self.TilesMainBox)
        self.Passability.setObjectName(_fromUtf8("Passability"))
        self.height_3 = QtGui.QHBoxLayout(self.Passability)
        self.height_3.setMargin(0)
        self.height_3.setMargin(0)
        self.height_3.setObjectName(_fromUtf8("height_3"))
        self.label_29 = QtGui.QLabel(self.Passability)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.height_3.addWidget(self.label_29)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.height_3.addItem(spacerItem4)
        self.TilesOffestYSpin_2 = QtGui.QDoubleSpinBox(self.Passability)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TilesOffestYSpin_2.sizePolicy().hasHeightForWidth())
        self.TilesOffestYSpin_2.setSizePolicy(sizePolicy)
        self.TilesOffestYSpin_2.setMinimumSize(QtCore.QSize(120, 0))
        self.TilesOffestYSpin_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TilesOffestYSpin_2.setAccelerated(False)
        self.TilesOffestYSpin_2.setMaximum(1.0)
        self.TilesOffestYSpin_2.setSingleStep(0.1)
        self.TilesOffestYSpin_2.setProperty("value", 1.0)
        self.TilesOffestYSpin_2.setObjectName(_fromUtf8("TilesOffestYSpin_2"))
        self.height_3.addWidget(self.TilesOffestYSpin_2)
        self.Multipler_23 = QtGui.QWidget(self.Passability)
        self.Multipler_23.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Multipler_23.setObjectName(_fromUtf8("Multipler_23"))
        self.horizontalLayout_71 = QtGui.QHBoxLayout(self.Multipler_23)
        self.horizontalLayout_71.setMargin(0)
        self.horizontalLayout_71.setMargin(0)
        self.horizontalLayout_71.setObjectName(_fromUtf8("horizontalLayout_71"))
        self.label_124 = QtGui.QLabel(self.Multipler_23)
        self.label_124.setObjectName(_fromUtf8("label_124"))
        self.horizontalLayout_71.addWidget(self.label_124)
        self.spinBox_98 = QtGui.QSpinBox(self.Multipler_23)
        self.spinBox_98.setMaximumSize(QtCore.QSize(48, 16777215))
        self.spinBox_98.setMinimum(1)
        self.spinBox_98.setMaximum(999)
        self.spinBox_98.setObjectName(_fromUtf8("spinBox_98"))
        self.horizontalLayout_71.addWidget(self.spinBox_98)
        self.height_3.addWidget(self.Multipler_23)
        self.verticalLayout_15.addWidget(self.Passability)
        self.Backing = QtGui.QWidget(self.TilesMainBox)
        self.Backing.setObjectName(_fromUtf8("Backing"))
        self.width_2 = QtGui.QHBoxLayout(self.Backing)
        self.width_2.setMargin(0)
        self.width_2.setMargin(0)
        self.width_2.setObjectName(_fromUtf8("width_2"))
        self.label_27 = QtGui.QLabel(self.Backing)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.width_2.addWidget(self.label_27)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.width_2.addItem(spacerItem5)
        self.checkBox = QtGui.QCheckBox(self.Backing)
        self.checkBox.setText(_fromUtf8(""))
        self.checkBox.setChecked(False)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.width_2.addWidget(self.checkBox)
        self.verticalLayout_15.addWidget(self.Backing)
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.TilesMainBox)
        self.groupBox_8 = QtGui.QGroupBox(self.MapTilesTab)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.TileImageViewer = YImageViewWidget(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TileImageViewer.sizePolicy().hasHeightForWidth())
        self.TileImageViewer.setSizePolicy(sizePolicy)
        self.TileImageViewer.setMinimumSize(QtCore.QSize(64, 64))
        self.TileImageViewer.setStyleSheet(_fromUtf8("background: transparent;"))
        self.TileImageViewer.setObjectName(_fromUtf8("TileImageViewer"))
        self.horizontalLayout_6.addWidget(self.TileImageViewer)
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.groupBox_8)
        self.MainTabs.addTab(self.MapTilesTab, _fromUtf8(""))
        self.MapTab = QtGui.QWidget()
        self.MapTab.setAutoFillBackground(False)
        self.MapTab.setObjectName(_fromUtf8("MapTab"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.MapTab)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.MapElements = QtGui.QToolBox(self.MapTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MapElements.sizePolicy().hasHeightForWidth())
        self.MapElements.setSizePolicy(sizePolicy)
        self.MapElements.setMinimumSize(QtCore.QSize(280, 0))
        self.MapElements.setMaximumSize(QtCore.QSize(280, 16777215))
        self.MapElements.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MapElements.setAutoFillBackground(False)
        self.MapElements.setStyleSheet(_fromUtf8("#MapElements::tab:selected { font: bold; height: 26px;} /* selected tab */\n"
"#MapElements::tab:!selected { height: 26px;} /* non-selected tab */\n"
"#MapElements{\n"
"border: 0px transparent;\n"
"}"))
        self.MapElements.setFrameShape(QtGui.QFrame.NoFrame)
        self.MapElements.setObjectName(_fromUtf8("MapElements"))
        self.MapTilesPage = QtGui.QWidget()
        self.MapTilesPage.setGeometry(QtCore.QRect(0, 0, 280, 517))
        self.MapTilesPage.setObjectName(_fromUtf8("MapTilesPage"))
        self.gridLayout = QtGui.QGridLayout(self.MapTilesPage)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.MapElements.addItem(self.MapTilesPage, _fromUtf8(""))
        self.MapObjectsPage = QtGui.QWidget()
        self.MapObjectsPage.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.MapObjectsPage.setObjectName(_fromUtf8("MapObjectsPage"))
        self.MapElements.addItem(self.MapObjectsPage, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.MapElements)
        self.verticalWidget = QtGui.QWidget(self.MapTab)
        self.verticalWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalWidget.setObjectName(_fromUtf8("verticalWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.MapAdditionalBox = QtGui.QGroupBox(self.verticalWidget)
        self.MapAdditionalBox.setCheckable(False)
        self.MapAdditionalBox.setObjectName(_fromUtf8("MapAdditionalBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.MapAdditionalBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.MapErase = QtGui.QPushButton(self.MapAdditionalBox)
        self.MapErase.setCheckable(True)
        self.MapErase.setChecked(False)
        self.MapErase.setAutoDefault(False)
        self.MapErase.setDefault(False)
        self.MapErase.setFlat(False)
        self.MapErase.setObjectName(_fromUtf8("MapErase"))
        self.verticalLayout_3.addWidget(self.MapErase)
        self.verticalLayout_2.addWidget(self.MapAdditionalBox)
        self.MapOptionsBox = QtGui.QGroupBox(self.verticalWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MapOptionsBox.sizePolicy().hasHeightForWidth())
        self.MapOptionsBox.setSizePolicy(sizePolicy)
        self.MapOptionsBox.setMinimumSize(QtCore.QSize(100, 480))
        self.MapOptionsBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MapOptionsBox.setAutoFillBackground(False)
        self.MapOptionsBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.MapOptionsBox.setFlat(False)
        self.MapOptionsBox.setCheckable(False)
        self.MapOptionsBox.setObjectName(_fromUtf8("MapOptionsBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.MapOptionsBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.ID_5 = YReadOnlySimpleInputWidget(self.MapOptionsBox)
        self.ID_5.setEnabled(True)
        self.ID_5.setObjectName(_fromUtf8("ID_5"))
        self.verticalLayout.addWidget(self.ID_5)
        self.RegionName = YSimpleInputWidget(self.MapOptionsBox)
        self.RegionName.setEnabled(True)
        self.RegionName.setObjectName(_fromUtf8("RegionName"))
        self.verticalLayout.addWidget(self.RegionName)
        self.Type_5 = YComboBoxWidget(self.MapOptionsBox)
        self.Type_5.setEnabled(True)
        self.Type_5.setObjectName(_fromUtf8("Type_5"))
        self.verticalLayout.addWidget(self.Type_5)
        self.MapBack = QtGui.QWidget(self.MapOptionsBox)
        self.MapBack.setObjectName(_fromUtf8("MapBack"))
        self.width_3 = QtGui.QHBoxLayout(self.MapBack)
        self.width_3.setMargin(0)
        self.width_3.setMargin(0)
        self.width_3.setObjectName(_fromUtf8("width_3"))
        self.label_30 = QtGui.QLabel(self.MapBack)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.width_3.addWidget(self.label_30)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.width_3.addItem(spacerItem6)
        self.checkBox_2 = QtGui.QCheckBox(self.MapBack)
        self.checkBox_2.setText(_fromUtf8(""))
        self.checkBox_2.setChecked(False)
        self.checkBox_2.setTristate(False)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.width_3.addWidget(self.checkBox_2)
        self.verticalLayout.addWidget(self.MapBack)
        self.BrushSize = QtGui.QWidget(self.MapOptionsBox)
        self.BrushSize.setEnabled(False)
        self.BrushSize.setObjectName(_fromUtf8("BrushSize"))
        self.width_4 = QtGui.QHBoxLayout(self.BrushSize)
        self.width_4.setMargin(0)
        self.width_4.setMargin(0)
        self.width_4.setObjectName(_fromUtf8("width_4"))
        self.label_31 = QtGui.QLabel(self.BrushSize)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.width_4.addWidget(self.label_31)
        self.horizontalScrollBar = QtGui.QScrollBar(self.BrushSize)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalScrollBar.sizePolicy().hasHeightForWidth())
        self.horizontalScrollBar.setSizePolicy(sizePolicy)
        self.horizontalScrollBar.setMinimum(1)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName(_fromUtf8("horizontalScrollBar"))
        self.width_4.addWidget(self.horizontalScrollBar)
        self.spinBox_2 = QtGui.QSpinBox(self.BrushSize)
        self.spinBox_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.spinBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(99)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.width_4.addWidget(self.spinBox_2)
        self.verticalLayout.addWidget(self.BrushSize)
        spacerItem7 = QtGui.QSpacerItem(20, 416, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.verticalLayout_2.addWidget(self.MapOptionsBox)
        self.horizontalLayout.addWidget(self.verticalWidget)
        spacerItem8 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.MainTabs.addTab(self.MapTab, _fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.MainTabs)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addWidget(self.widget)
        self.folder = QtGui.QHBoxLayout()
        self.folder.setObjectName(_fromUtf8("folder"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.folder.addWidget(self.label)
        self.FolderPlace = QtGui.QLineEdit(self.centralwidget)
        self.FolderPlace.setReadOnly(True)
        self.FolderPlace.setObjectName(_fromUtf8("FolderPlace"))
        self.folder.addWidget(self.FolderPlace)
        self.OpenFolderDBox = QtGui.QDialogButtonBox(self.centralwidget)
        self.OpenFolderDBox.setMaximumSize(QtCore.QSize(75, 16777215))
        self.OpenFolderDBox.setOrientation(QtCore.Qt.Horizontal)
        self.OpenFolderDBox.setStandardButtons(QtGui.QDialogButtonBox.Open)
        self.OpenFolderDBox.setCenterButtons(False)
        self.OpenFolderDBox.setObjectName(_fromUtf8("OpenFolderDBox"))
        self.folder.addWidget(self.OpenFolderDBox)
        self.verticalLayout_4.addLayout(self.folder)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.exitbox = QtGui.QDialogButtonBox(self.centralwidget)
        self.exitbox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.RestoreDefaults|QtGui.QDialogButtonBox.Save)
        self.exitbox.setCenterButtons(False)
        self.exitbox.setObjectName(_fromUtf8("exitbox"))
        self.horizontalLayout_2.addWidget(self.exitbox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        Editor.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Editor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 821, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuEditor = QtGui.QMenu(self.menubar)
        self.menuEditor.setObjectName(_fromUtf8("menuEditor"))
        Editor.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Editor)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Editor.setStatusBar(self.statusbar)
        self.actionGeneralConfig = QtGui.QAction(Editor)
        self.actionGeneralConfig.setObjectName(_fromUtf8("actionGeneralConfig"))
        self.actionQuit = QtGui.QAction(Editor)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuEditor.addAction(self.actionGeneralConfig)
        self.menuEditor.addAction(self.actionQuit)
        self.menubar.addAction(self.menuEditor.menuAction())

        self.retranslateUi(Editor)
        self.MainTabs.setCurrentIndex(1)
        self.MapElements.setCurrentIndex(0)
        QtCore.QObject.connect(self.horizontalScrollBar, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_2.setValue)
        QtCore.QObject.connect(self.spinBox_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalScrollBar.setValue)
        QtCore.QObject.connect(self.Image_5, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), self.SpriteImageViewer.setImage)
        QtCore.QObject.connect(self.SpriteImageViewer, QtCore.SIGNAL(_fromUtf8("widthChanged(int)")), self.Width_2.setValue)
        QtCore.QObject.connect(self.SpriteImageViewer, QtCore.SIGNAL(_fromUtf8("heightChanged(int)")), self.Height_2.setValue)
        QtCore.QObject.connect(self.Width_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.SpriteImageViewer.setAreaWidth)
        QtCore.QObject.connect(self.Height_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.SpriteImageViewer.setAreaHeight)
        QtCore.QObject.connect(self.OffsetY, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.SpriteImageViewer.setY)
        QtCore.QObject.connect(self.OffsetX, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.SpriteImageViewer.setX)
        QtCore.QObject.connect(self.Rows, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.SpriteImageViewer.setRows)
        QtCore.QObject.connect(self.Columns, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.SpriteImageViewer.setColumns)
        QtCore.QObject.connect(self.SpriteImageViewer, QtCore.SIGNAL(_fromUtf8("xChanged(int)")), self.OffsetX.setValue)
        QtCore.QObject.connect(self.SpriteImageViewer, QtCore.SIGNAL(_fromUtf8("yChanged(int)")), self.OffsetY.setValue)
        QtCore.QObject.connect(self.OpenFolderDBox, QtCore.SIGNAL(_fromUtf8("clicked(QAbstractButton*)")), Editor.openFolder)
        QtCore.QObject.connect(self.NewConfigButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Editor.createConfigFile)
        QtCore.QObject.connect(self.NewEntryButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Editor.createConfigRecord)
        QtCore.QObject.connect(self.exitbox, QtCore.SIGNAL(_fromUtf8("accepted()")), Editor.saveFile)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.close)
        QtCore.QObject.connect(self.MainTabs, QtCore.SIGNAL(_fromUtf8("currentChanged(int)")), Editor.reloadFiles)
        QtCore.QObject.connect(self.FilesList, QtCore.SIGNAL(_fromUtf8("itemActivated(QListWidgetItem*)")), Editor.reloadElements)
        QtCore.QObject.connect(self.ItemsList, QtCore.SIGNAL(_fromUtf8("itemActivated(QListWidgetItem*)")), Editor.reloadContent)
        QtCore.QObject.connect(self.exitbox, QtCore.SIGNAL(_fromUtf8("rejected()")), Editor.close)
        QtCore.QObject.connect(self.Picture_2, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Editor.loadTileImage)
        QtCore.QObject.connect(self.Animation, QtCore.SIGNAL(_fromUtf8("changed(PyQt_PyObject)")), self.EntityAnimationSettings.updateData)
        QtCore.QObject.connect(self.Image_3, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), self.EntityAnimationSettings.updateTypes)
        QtCore.QMetaObject.connectSlotsByName(Editor)
        Editor.setTabOrder(self.FolderPlace, self.exitbox)

    def retranslateUi(self, Editor):
        Editor.setWindowTitle(QtGui.QApplication.translate("Editor", "Yukkuri Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Editor", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.NewConfigButton.setText(QtGui.QApplication.translate("Editor", "New config file", None, QtGui.QApplication.UnicodeUTF8))
        self.NewEntryButton.setText(QtGui.QApplication.translate("Editor", "New entry", None, QtGui.QApplication.UnicodeUTF8))
        self.SpritesMainBox.setTitle(QtGui.QApplication.translate("Editor", "Main", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("Editor", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.SpriteTab), QtGui.QApplication.translate("Editor", "Sprites", None, QtGui.QApplication.UnicodeUTF8))
        self.EntityMainBox.setTitle(QtGui.QApplication.translate("Editor", "Main", None, QtGui.QApplication.UnicodeUTF8))
        self.EntityEntityBox.setTitle(QtGui.QApplication.translate("Editor", "Entity", None, QtGui.QApplication.UnicodeUTF8))
        self.EntityFeedBox.setTitle(QtGui.QApplication.translate("Editor", "Feed", None, QtGui.QApplication.UnicodeUTF8))
        self.EntityMiscBox.setTitle(QtGui.QApplication.translate("Editor", "Misc", None, QtGui.QApplication.UnicodeUTF8))
        self.EntityAnimationBox.setTitle(QtGui.QApplication.translate("Editor", "Animation", None, QtGui.QApplication.UnicodeUTF8))
        self.EntityAnimaptionPreview.setTitle(QtGui.QApplication.translate("Editor", "Animation preview", None, QtGui.QApplication.UnicodeUTF8))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.EntityTab), QtGui.QApplication.translate("Editor", "Entity", None, QtGui.QApplication.UnicodeUTF8))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.WidgetsTab), QtGui.QApplication.translate("Editor", "Widgets", None, QtGui.QApplication.UnicodeUTF8))
        self.TilesMainBox.setTitle(QtGui.QApplication.translate("Editor", "Main", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Editor", "Passability:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_124.setText(QtGui.QApplication.translate("Editor", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Editor", "Backing:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("Editor", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.MapTilesTab), QtGui.QApplication.translate("Editor", "Tiles", None, QtGui.QApplication.UnicodeUTF8))
        self.MapElements.setItemText(self.MapElements.indexOf(self.MapTilesPage), QtGui.QApplication.translate("Editor", "Tiles", None, QtGui.QApplication.UnicodeUTF8))
        self.MapElements.setItemText(self.MapElements.indexOf(self.MapObjectsPage), QtGui.QApplication.translate("Editor", "Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.MapAdditionalBox.setTitle(QtGui.QApplication.translate("Editor", "Additional", None, QtGui.QApplication.UnicodeUTF8))
        self.MapErase.setText(QtGui.QApplication.translate("Editor", "Erase", None, QtGui.QApplication.UnicodeUTF8))
        self.MapOptionsBox.setTitle(QtGui.QApplication.translate("Editor", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("Editor", "Backing:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("Editor", "Brush size:", None, QtGui.QApplication.UnicodeUTF8))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.MapTab), QtGui.QApplication.translate("Editor", "Map", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Editor", "Source files directory path:", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEditor.setTitle(QtGui.QApplication.translate("Editor", "Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGeneralConfig.setText(QtGui.QApplication.translate("Editor", "General config", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("Editor", "Quit", None, QtGui.QApplication.UnicodeUTF8))

from widgets import YTableWidget, YSpinBoxInputWidget, YFileInputWidget, YColorInputWidget, YAnimationPreviewWidget, YImageViewWidget, YImageChooser, YComboBoxWidget, YReadOnlySimpleInputWidget, YDoubleSpinBoxInputWidget, YReadOnlySpinBoxInputWidget, YSimpleInputWidget
