# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Editor.ui'
#
# Created: Mon Oct  4 20:23:16 2010
#      by: PyQt4 UI code generator 4.7.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Editor(object):
    def setupUi(self, Editor):
        Editor.setObjectName(_fromUtf8("Editor"))
        Editor.resize(830, 699)
        self.centralwidget = QtGui.QWidget(Editor)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.widget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(150, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(230, 16777215))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.FilesList = QtGui.QListWidget(self.groupBox_2)
        self.FilesList.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.FilesList.setObjectName(_fromUtf8("FilesList"))
        self.verticalLayout_8.addWidget(self.FilesList)
        self.ItemsList = QtGui.QListWidget(self.groupBox_2)
        self.ItemsList.setObjectName(_fromUtf8("ItemsList"))
        self.verticalLayout_8.addWidget(self.ItemsList)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.MainTabs = QtGui.QTabWidget(self.widget)
        self.MainTabs.setObjectName(_fromUtf8("MainTabs"))
        self.EntityTab = QtGui.QWidget()
        self.EntityTab.setObjectName(_fromUtf8("EntityTab"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.EntityTab)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.EntityMainBox = QtGui.QGroupBox(self.EntityTab)
        self.EntityMainBox.setObjectName(_fromUtf8("EntityMainBox"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.EntityMainBox)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.Name = QtGui.QWidget(self.EntityMainBox)
        self.Name.setEnabled(True)
        self.Name.setObjectName(_fromUtf8("Name"))
        self.meeting_2 = QtGui.QHBoxLayout(self.Name)
        self.meeting_2.setMargin(0)
        self.meeting_2.setObjectName(_fromUtf8("meeting_2"))
        self.label_17 = QtGui.QLabel(self.Name)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.meeting_2.addWidget(self.label_17)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.meeting_2.addItem(spacerItem)
        self.lineEdit_21 = QtGui.QLineEdit(self.Name)
        self.lineEdit_21.setMinimumSize(QtCore.QSize(190, 0))
        self.lineEdit_21.setMaximumSize(QtCore.QSize(190, 16777215))
        self.lineEdit_21.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.meeting_2.addWidget(self.lineEdit_21)
        self.verticalLayout_7.addWidget(self.Name)
        self.Image_3 = QtGui.QWidget(self.EntityMainBox)
        self.Image_3.setObjectName(_fromUtf8("Image_3"))
        self.Image = QtGui.QHBoxLayout(self.Image_3)
        self.Image.setMargin(0)
        self.Image.setObjectName(_fromUtf8("Image"))
        self.label_2 = QtGui.QLabel(self.Image_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.Image.addWidget(self.label_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Image.addItem(spacerItem1)
        self.EntityImgField = QtGui.QLineEdit(self.Image_3)
        self.EntityImgField.setMaximumSize(QtCore.QSize(190, 16777215))
        self.EntityImgField.setObjectName(_fromUtf8("EntityImgField"))
        self.Image.addWidget(self.EntityImgField)
        self.EntityImgButton = QtGui.QDialogButtonBox(self.Image_3)
        self.EntityImgButton.setMaximumSize(QtCore.QSize(75, 16777215))
        self.EntityImgButton.setStandardButtons(QtGui.QDialogButtonBox.Open)
        self.EntityImgButton.setObjectName(_fromUtf8("EntityImgButton"))
        self.Image.addWidget(self.EntityImgButton)
        self.verticalLayout_7.addWidget(self.Image_3)
        self.Imagecols = QtGui.QWidget(self.EntityMainBox)
        self.Imagecols.setObjectName(_fromUtf8("Imagecols"))
        self.imagecols = QtGui.QHBoxLayout(self.Imagecols)
        self.imagecols.setMargin(0)
        self.imagecols.setObjectName(_fromUtf8("imagecols"))
        self.label_3 = QtGui.QLabel(self.Imagecols)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.imagecols.addWidget(self.label_3)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.imagecols.addItem(spacerItem2)
        self.lineEdit_3 = QtGui.QLineEdit(self.Imagecols)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(190, 0))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(190, 16777215))
        self.lineEdit_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.imagecols.addWidget(self.lineEdit_3)
        self.verticalLayout_7.addWidget(self.Imagecols)
        self.Imagerows = QtGui.QWidget(self.EntityMainBox)
        self.Imagerows.setObjectName(_fromUtf8("Imagerows"))
        self.imagerows = QtGui.QHBoxLayout(self.Imagerows)
        self.imagerows.setMargin(0)
        self.imagerows.setObjectName(_fromUtf8("imagerows"))
        self.label_4 = QtGui.QLabel(self.Imagerows)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.imagerows.addWidget(self.label_4)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.imagerows.addItem(spacerItem3)
        self.lineEdit_4 = QtGui.QLineEdit(self.Imagerows)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(190, 0))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(190, 16777215))
        self.lineEdit_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.imagerows.addWidget(self.lineEdit_4)
        self.verticalLayout_7.addWidget(self.Imagerows)
        self.Height = QtGui.QWidget(self.EntityMainBox)
        self.Height.setObjectName(_fromUtf8("Height"))
        self.height = QtGui.QHBoxLayout(self.Height)
        self.height.setMargin(0)
        self.height.setObjectName(_fromUtf8("height"))
        self.label_5 = QtGui.QLabel(self.Height)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.height.addWidget(self.label_5)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.height.addItem(spacerItem4)
        self.lineEdit_5 = QtGui.QLineEdit(self.Height)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(190, 0))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(190, 16777215))
        self.lineEdit_5.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.height.addWidget(self.lineEdit_5)
        self.verticalLayout_7.addWidget(self.Height)
        self.Width = QtGui.QWidget(self.EntityMainBox)
        self.Width.setObjectName(_fromUtf8("Width"))
        self.width = QtGui.QHBoxLayout(self.Width)
        self.width.setMargin(0)
        self.width.setObjectName(_fromUtf8("width"))
        self.label_7 = QtGui.QLabel(self.Width)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.width.addWidget(self.label_7)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.width.addItem(spacerItem5)
        self.lineEdit_7 = QtGui.QLineEdit(self.Width)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(190, 0))
        self.lineEdit_7.setMaximumSize(QtCore.QSize(190, 16777215))
        self.lineEdit_7.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.width.addWidget(self.lineEdit_7)
        self.verticalLayout_7.addWidget(self.Width)
        self.Meeting = QtGui.QWidget(self.EntityMainBox)
        self.Meeting.setObjectName(_fromUtf8("Meeting"))
        self.meeting = QtGui.QHBoxLayout(self.Meeting)
        self.meeting.setMargin(0)
        self.meeting.setObjectName(_fromUtf8("meeting"))
        self.label_8 = QtGui.QLabel(self.Meeting)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.meeting.addWidget(self.label_8)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.meeting.addItem(spacerItem6)
        self.lineEdit_8 = QtGui.QLineEdit(self.Meeting)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(190, 0))
        self.lineEdit_8.setMaximumSize(QtCore.QSize(190, 16777215))
        self.lineEdit_8.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.meeting.addWidget(self.lineEdit_8)
        self.verticalLayout_7.addWidget(self.Meeting)
        self.verticalLayout_10.addWidget(self.EntityMainBox)
        self.EntityEntityBox = QtGui.QGroupBox(self.EntityTab)
        self.EntityEntityBox.setObjectName(_fromUtf8("EntityEntityBox"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.EntityEntityBox)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.Damage = QtGui.QWidget(self.EntityEntityBox)
        self.Damage.setObjectName(_fromUtf8("Damage"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.Damage)
        self.horizontalLayout_16.setMargin(0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_10 = QtGui.QLabel(self.Damage)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_16.addWidget(self.label_10)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem7)
        self.lineEdit_10 = QtGui.QLineEdit(self.Damage)
        self.lineEdit_10.setMinimumSize(QtCore.QSize(190, 0))
        self.lineEdit_10.setMaximumSize(QtCore.QSize(190, 16777215))
        self.lineEdit_10.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.horizontalLayout_16.addWidget(self.lineEdit_10)
        self.verticalLayout_12.addWidget(self.Damage)
        self.Speed = QtGui.QWidget(self.EntityEntityBox)
        self.Speed.setObjectName(_fromUtf8("Speed"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.Speed)
        self.horizontalLayout_18.setMargin(0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_12 = QtGui.QLabel(self.Speed)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_18.addWidget(self.label_12)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem8)
        self.lineEdit_12 = QtGui.QLineEdit(self.Speed)
        self.lineEdit_12.setMinimumSize(QtCore.QSize(190, 0))
        self.lineEdit_12.setMaximumSize(QtCore.QSize(190, 16777215))
        self.lineEdit_12.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.horizontalLayout_18.addWidget(self.lineEdit_12)
        self.verticalLayout_12.addWidget(self.Speed)
        self.Bloodcolor = QtGui.QWidget(self.EntityEntityBox)
        self.Bloodcolor.setObjectName(_fromUtf8("Bloodcolor"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.Bloodcolor)
        self.horizontalLayout_20.setMargin(0)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_14 = QtGui.QLabel(self.Bloodcolor)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_20.addWidget(self.label_14)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem9)
        self.lineEdit_6 = QtGui.QLineEdit(self.Bloodcolor)
        self.lineEdit_6.setMaximumSize(QtCore.QSize(45, 16777215))
        self.lineEdit_6.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_6.setMaxLength(3)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.horizontalLayout_20.addWidget(self.lineEdit_6)
        self.lineEdit_14 = QtGui.QLineEdit(self.Bloodcolor)
        self.lineEdit_14.setMaximumSize(QtCore.QSize(45, 16777215))
        self.lineEdit_14.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_14.setMaxLength(3)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.horizontalLayout_20.addWidget(self.lineEdit_14)
        self.lineEdit_15 = QtGui.QLineEdit(self.Bloodcolor)
        self.lineEdit_15.setMaximumSize(QtCore.QSize(45, 16777215))
        self.lineEdit_15.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_15.setMaxLength(3)
        self.lineEdit_15.setFrame(True)
        self.lineEdit_15.setDragEnabled(False)
        self.lineEdit_15.setReadOnly(False)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.horizontalLayout_20.addWidget(self.lineEdit_15)
        self.toolButton = QtGui.QToolButton(self.Bloodcolor)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout_20.addWidget(self.toolButton)
        self.verticalLayout_12.addWidget(self.Bloodcolor)
        self.verticalLayout_10.addWidget(self.EntityEntityBox)
        self.EntityFeedBox = QtGui.QGroupBox(self.EntityTab)
        self.EntityFeedBox.setObjectName(_fromUtf8("EntityFeedBox"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.EntityFeedBox)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.Nutritive = QtGui.QWidget(self.EntityFeedBox)
        self.Nutritive.setObjectName(_fromUtf8("Nutritive"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.Nutritive)
        self.horizontalLayout_17.setMargin(0)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_11 = QtGui.QLabel(self.Nutritive)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_17.addWidget(self.label_11)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem10)
        self.lineEdit_11 = QtGui.QLineEdit(self.Nutritive)
        self.lineEdit_11.setMinimumSize(QtCore.QSize(190, 0))
        self.lineEdit_11.setMaximumSize(QtCore.QSize(190, 16777215))
        self.lineEdit_11.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.horizontalLayout_17.addWidget(self.lineEdit_11)
        self.verticalLayout_11.addWidget(self.Nutritive)
        self.verticalLayout_10.addWidget(self.EntityFeedBox)
        self.EntityMiscBox = QtGui.QGroupBox(self.EntityTab)
        self.EntityMiscBox.setObjectName(_fromUtf8("EntityMiscBox"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.EntityMiscBox)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.Hp = QtGui.QWidget(self.EntityMiscBox)
        self.Hp.setObjectName(_fromUtf8("Hp"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.Hp)
        self.horizontalLayout_19.setMargin(0)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_13 = QtGui.QLabel(self.Hp)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_19.addWidget(self.label_13)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem11)
        self.lineEdit_13 = QtGui.QLineEdit(self.Hp)
        self.lineEdit_13.setMinimumSize(QtCore.QSize(190, 0))
        self.lineEdit_13.setMaximumSize(QtCore.QSize(190, 16777215))
        self.lineEdit_13.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.horizontalLayout_19.addWidget(self.lineEdit_13)
        self.verticalLayout_13.addWidget(self.Hp)
        self.verticalLayout_10.addWidget(self.EntityMiscBox)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem12)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.EntityAnimationBox = QtGui.QGroupBox(self.EntityTab)
        self.EntityAnimationBox.setObjectName(_fromUtf8("EntityAnimationBox"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.EntityAnimationBox)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.Up = QtGui.QWidget(self.EntityAnimationBox)
        self.Up.setObjectName(_fromUtf8("Up"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.Up)
        self.horizontalLayout_15.setMargin(0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_9 = QtGui.QLabel(self.Up)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_15.addWidget(self.label_9)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem13)
        self.lineEdit_16 = QtGui.QLineEdit(self.Up)
        self.lineEdit_16.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_16.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_16.setBaseSize(QtCore.QSize(80, 0))
        self.lineEdit_16.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_16.setMaxLength(3)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.horizontalLayout_15.addWidget(self.lineEdit_16)
        self.lineEdit_9 = QtGui.QLineEdit(self.Up)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_9.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_9.setBaseSize(QtCore.QSize(80, 0))
        self.lineEdit_9.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_9.setMaxLength(3)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.horizontalLayout_15.addWidget(self.lineEdit_9)
        self.verticalLayout_9.addWidget(self.Up)
        self.Rightup = QtGui.QWidget(self.EntityAnimationBox)
        self.Rightup.setObjectName(_fromUtf8("Rightup"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout(self.Rightup)
        self.horizontalLayout_27.setMargin(0)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_21 = QtGui.QLabel(self.Rightup)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_27.addWidget(self.label_21)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem14)
        self.lineEdit_29 = QtGui.QLineEdit(self.Rightup)
        self.lineEdit_29.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_29.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_29.setBaseSize(QtCore.QSize(80, 0))
        self.lineEdit_29.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_29.setMaxLength(3)
        self.lineEdit_29.setObjectName(_fromUtf8("lineEdit_29"))
        self.horizontalLayout_27.addWidget(self.lineEdit_29)
        self.lineEdit_30 = QtGui.QLineEdit(self.Rightup)
        self.lineEdit_30.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_30.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_30.setBaseSize(QtCore.QSize(80, 0))
        self.lineEdit_30.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_30.setMaxLength(3)
        self.lineEdit_30.setObjectName(_fromUtf8("lineEdit_30"))
        self.horizontalLayout_27.addWidget(self.lineEdit_30)
        self.verticalLayout_9.addWidget(self.Rightup)
        self.Right = QtGui.QWidget(self.EntityAnimationBox)
        self.Right.setObjectName(_fromUtf8("Right"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.Right)
        self.horizontalLayout_22.setMargin(0)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_16 = QtGui.QLabel(self.Right)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_22.addWidget(self.label_16)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem15)
        self.lineEdit_19 = QtGui.QLineEdit(self.Right)
        self.lineEdit_19.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_19.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_19.setBaseSize(QtCore.QSize(80, 0))
        self.lineEdit_19.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_19.setMaxLength(3)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.horizontalLayout_22.addWidget(self.lineEdit_19)
        self.lineEdit_20 = QtGui.QLineEdit(self.Right)
        self.lineEdit_20.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_20.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_20.setBaseSize(QtCore.QSize(80, 0))
        self.lineEdit_20.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_20.setMaxLength(3)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.horizontalLayout_22.addWidget(self.lineEdit_20)
        self.verticalLayout_9.addWidget(self.Right)
        self.Rightdown = QtGui.QWidget(self.EntityAnimationBox)
        self.Rightdown.setObjectName(_fromUtf8("Rightdown"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout(self.Rightdown)
        self.horizontalLayout_28.setMargin(0)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_22 = QtGui.QLabel(self.Rightdown)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_28.addWidget(self.label_22)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem16)
        self.lineEdit_31 = QtGui.QLineEdit(self.Rightdown)
        self.lineEdit_31.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_31.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_31.setBaseSize(QtCore.QSize(80, 0))
        self.lineEdit_31.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_31.setMaxLength(3)
        self.lineEdit_31.setObjectName(_fromUtf8("lineEdit_31"))
        self.horizontalLayout_28.addWidget(self.lineEdit_31)
        self.lineEdit_32 = QtGui.QLineEdit(self.Rightdown)
        self.lineEdit_32.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_32.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_32.setBaseSize(QtCore.QSize(80, 0))
        self.lineEdit_32.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_32.setMaxLength(3)
        self.lineEdit_32.setObjectName(_fromUtf8("lineEdit_32"))
        self.horizontalLayout_28.addWidget(self.lineEdit_32)
        self.verticalLayout_9.addWidget(self.Rightdown)
        self.Down = QtGui.QWidget(self.EntityAnimationBox)
        self.Down.setObjectName(_fromUtf8("Down"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.Down)
        self.horizontalLayout_29.setMargin(0)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.label_23 = QtGui.QLabel(self.Down)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_29.addWidget(self.label_23)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem17)
        self.lineEdit_33 = QtGui.QLineEdit(self.Down)
        self.lineEdit_33.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_33.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_33.setBaseSize(QtCore.QSize(80, 0))
        self.lineEdit_33.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_33.setMaxLength(3)
        self.lineEdit_33.setObjectName(_fromUtf8("lineEdit_33"))
        self.horizontalLayout_29.addWidget(self.lineEdit_33)
        self.lineEdit_34 = QtGui.QLineEdit(self.Down)
        self.lineEdit_34.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_34.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_34.setBaseSize(QtCore.QSize(80, 0))
        self.lineEdit_34.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_34.setMaxLength(3)
        self.lineEdit_34.setObjectName(_fromUtf8("lineEdit_34"))
        self.horizontalLayout_29.addWidget(self.lineEdit_34)
        self.verticalLayout_9.addWidget(self.Down)
        self.Leftdown = QtGui.QWidget(self.EntityAnimationBox)
        self.Leftdown.setObjectName(_fromUtf8("Leftdown"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.Leftdown)
        self.horizontalLayout_21.setMargin(0)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_15 = QtGui.QLabel(self.Leftdown)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_21.addWidget(self.label_15)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem18)
        self.lineEdit_17 = QtGui.QLineEdit(self.Leftdown)
        self.lineEdit_17.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_17.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_17.setBaseSize(QtCore.QSize(80, 0))
        self.lineEdit_17.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_17.setMaxLength(3)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.horizontalLayout_21.addWidget(self.lineEdit_17)
        self.lineEdit_18 = QtGui.QLineEdit(self.Leftdown)
        self.lineEdit_18.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_18.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_18.setBaseSize(QtCore.QSize(80, 0))
        self.lineEdit_18.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_18.setMaxLength(3)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.horizontalLayout_21.addWidget(self.lineEdit_18)
        self.verticalLayout_9.addWidget(self.Leftdown)
        self.Left = QtGui.QWidget(self.EntityAnimationBox)
        self.Left.setObjectName(_fromUtf8("Left"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.Left)
        self.horizontalLayout_24.setMargin(0)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_18 = QtGui.QLabel(self.Left)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_24.addWidget(self.label_18)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem19)
        self.lineEdit_23 = QtGui.QLineEdit(self.Left)
        self.lineEdit_23.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_23.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_23.setBaseSize(QtCore.QSize(80, 0))
        self.lineEdit_23.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_23.setMaxLength(3)
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.horizontalLayout_24.addWidget(self.lineEdit_23)
        self.lineEdit_24 = QtGui.QLineEdit(self.Left)
        self.lineEdit_24.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_24.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_24.setBaseSize(QtCore.QSize(80, 0))
        self.lineEdit_24.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_24.setMaxLength(3)
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.horizontalLayout_24.addWidget(self.lineEdit_24)
        self.verticalLayout_9.addWidget(self.Left)
        self.Leftup = QtGui.QWidget(self.EntityAnimationBox)
        self.Leftup.setObjectName(_fromUtf8("Leftup"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout(self.Leftup)
        self.horizontalLayout_26.setMargin(0)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_19 = QtGui.QLabel(self.Leftup)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_26.addWidget(self.label_19)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem20)
        self.lineEdit_27 = QtGui.QLineEdit(self.Leftup)
        self.lineEdit_27.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_27.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_27.setBaseSize(QtCore.QSize(80, 0))
        self.lineEdit_27.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_27.setMaxLength(3)
        self.lineEdit_27.setObjectName(_fromUtf8("lineEdit_27"))
        self.horizontalLayout_26.addWidget(self.lineEdit_27)
        self.lineEdit_28 = QtGui.QLineEdit(self.Leftup)
        self.lineEdit_28.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_28.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_28.setBaseSize(QtCore.QSize(80, 0))
        self.lineEdit_28.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_28.setMaxLength(3)
        self.lineEdit_28.setObjectName(_fromUtf8("lineEdit_28"))
        self.horizontalLayout_26.addWidget(self.lineEdit_28)
        self.verticalLayout_9.addWidget(self.Leftup)
        self.verticalLayout_14.addWidget(self.EntityAnimationBox)
        spacerItem21 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem21)
        self.horizontalLayout_4.addLayout(self.verticalLayout_14)
        self.MainTabs.addTab(self.EntityTab, _fromUtf8(""))
        self.WidgetsTab = QtGui.QWidget()
        self.WidgetsTab.setObjectName(_fromUtf8("WidgetsTab"))
        self.MainTabs.addTab(self.WidgetsTab, _fromUtf8(""))
        self.MapTilesTab = QtGui.QWidget()
        self.MapTilesTab.setObjectName(_fromUtf8("MapTilesTab"))
        self.formLayout_2 = QtGui.QFormLayout(self.MapTilesTab)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.TilesMainBox = QtGui.QGroupBox(self.MapTilesTab)
        self.TilesMainBox.setObjectName(_fromUtf8("TilesMainBox"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.TilesMainBox)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.Name_2 = QtGui.QWidget(self.TilesMainBox)
        self.Name_2.setObjectName(_fromUtf8("Name_2"))
        self.imgcols_3 = QtGui.QHBoxLayout(self.Name_2)
        self.imgcols_3.setMargin(0)
        self.imgcols_3.setObjectName(_fromUtf8("imgcols_3"))
        self.label_28 = QtGui.QLabel(self.Name_2)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.imgcols_3.addWidget(self.label_28)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.imgcols_3.addItem(spacerItem22)
        self.lineEdit_37 = QtGui.QLineEdit(self.Name_2)
        self.lineEdit_37.setMinimumSize(QtCore.QSize(190, 0))
        self.lineEdit_37.setMaximumSize(QtCore.QSize(190, 16777215))
        self.lineEdit_37.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_37.setObjectName(_fromUtf8("lineEdit_37"))
        self.imgcols_3.addWidget(self.lineEdit_37)
        self.verticalLayout_15.addWidget(self.Name_2)
        self.Image_4 = QtGui.QWidget(self.TilesMainBox)
        self.Image_4.setObjectName(_fromUtf8("Image_4"))
        self.Image_2 = QtGui.QHBoxLayout(self.Image_4)
        self.Image_2.setMargin(0)
        self.Image_2.setObjectName(_fromUtf8("Image_2"))
        self.label_6 = QtGui.QLabel(self.Image_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.Image_2.addWidget(self.label_6)
        self.lineEdit_35 = QtGui.QLineEdit(self.Image_4)
        self.lineEdit_35.setMaximumSize(QtCore.QSize(190, 16777215))
        self.lineEdit_35.setObjectName(_fromUtf8("lineEdit_35"))
        self.Image_2.addWidget(self.lineEdit_35)
        self.dialogButtonBox = QtGui.QDialogButtonBox(self.Image_4)
        self.dialogButtonBox.setMaximumSize(QtCore.QSize(75, 16777215))
        self.dialogButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Open)
        self.dialogButtonBox.setObjectName(_fromUtf8("dialogButtonBox"))
        self.Image_2.addWidget(self.dialogButtonBox)
        self.verticalLayout_15.addWidget(self.Image_4)
        self.OffsetX = QtGui.QWidget(self.TilesMainBox)
        self.OffsetX.setObjectName(_fromUtf8("OffsetX"))
        self.imgrows_2 = QtGui.QHBoxLayout(self.OffsetX)
        self.imgrows_2.setMargin(0)
        self.imgrows_2.setObjectName(_fromUtf8("imgrows_2"))
        self.label_25 = QtGui.QLabel(self.OffsetX)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.imgrows_2.addWidget(self.label_25)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.imgrows_2.addItem(spacerItem23)
        self.TilesOffestXSpin = QtGui.QDoubleSpinBox(self.OffsetX)
        self.TilesOffestXSpin.setObjectName(_fromUtf8("TilesOffestXSpin"))
        self.imgrows_2.addWidget(self.TilesOffestXSpin)
        self.verticalLayout_15.addWidget(self.OffsetX)
        self.OffsetY = QtGui.QWidget(self.TilesMainBox)
        self.OffsetY.setObjectName(_fromUtf8("OffsetY"))
        self.height_2 = QtGui.QHBoxLayout(self.OffsetY)
        self.height_2.setMargin(0)
        self.height_2.setObjectName(_fromUtf8("height_2"))
        self.label_26 = QtGui.QLabel(self.OffsetY)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.height_2.addWidget(self.label_26)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.height_2.addItem(spacerItem24)
        self.TilesOffestYSpin = QtGui.QDoubleSpinBox(self.OffsetY)
        self.TilesOffestYSpin.setObjectName(_fromUtf8("TilesOffestYSpin"))
        self.height_2.addWidget(self.TilesOffestYSpin)
        self.verticalLayout_15.addWidget(self.OffsetY)
        self.Blocked = QtGui.QWidget(self.TilesMainBox)
        self.Blocked.setObjectName(_fromUtf8("Blocked"))
        self.width_2 = QtGui.QHBoxLayout(self.Blocked)
        self.width_2.setMargin(0)
        self.width_2.setObjectName(_fromUtf8("width_2"))
        self.label_27 = QtGui.QLabel(self.Blocked)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.width_2.addWidget(self.label_27)
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.width_2.addItem(spacerItem25)
        self.checkBox = QtGui.QCheckBox(self.Blocked)
        self.checkBox.setText(_fromUtf8(""))
        self.checkBox.setChecked(False)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.width_2.addWidget(self.checkBox)
        self.verticalLayout_15.addWidget(self.Blocked)
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.TilesMainBox)
        self.groupBox_8 = QtGui.QGroupBox(self.MapTilesTab)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.TileImageViewer = QtGui.QLabel(self.groupBox_8)
        self.TileImageViewer.setEnabled(True)
        self.TileImageViewer.setMinimumSize(QtCore.QSize(64, 64))
        self.TileImageViewer.setMaximumSize(QtCore.QSize(128, 128))
        self.TileImageViewer.setFrameShape(QtGui.QFrame.NoFrame)
        self.TileImageViewer.setText(_fromUtf8(""))
        self.TileImageViewer.setScaledContents(False)
        self.TileImageViewer.setAlignment(QtCore.Qt.AlignCenter)
        self.TileImageViewer.setIndent(0)
        self.TileImageViewer.setObjectName(_fromUtf8("TileImageViewer"))
        self.horizontalLayout_6.addWidget(self.TileImageViewer)
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.groupBox_8)
        self.MainTabs.addTab(self.MapTilesTab, _fromUtf8(""))
        self.MapTab = QtGui.QWidget()
        self.MapTab.setObjectName(_fromUtf8("MapTab"))
        self.gridLayout = QtGui.QGridLayout(self.MapTab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.comboBox = QtGui.QComboBox(self.MapTab)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.gridLayout.addWidget(self.comboBox, 0, 0, 1, 1)
        self.groupBox_9 = QtGui.QGroupBox(self.MapTab)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.TileImageViewer_2 = QtGui.QLabel(self.groupBox_9)
        self.TileImageViewer_2.setMinimumSize(QtCore.QSize(60, 60))
        self.TileImageViewer_2.setText(_fromUtf8(""))
        self.TileImageViewer_2.setObjectName(_fromUtf8("TileImageViewer_2"))
        self.horizontalLayout_7.addWidget(self.TileImageViewer_2)
        self.gridLayout.addWidget(self.groupBox_9, 1, 0, 1, 1)
        self.MainTabs.addTab(self.MapTab, _fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.MainTabs)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addWidget(self.widget)
        self.folder = QtGui.QHBoxLayout()
        self.folder.setObjectName(_fromUtf8("folder"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.folder.addWidget(self.label)
        self.FolderPlace = QtGui.QLineEdit(self.centralwidget)
        self.FolderPlace.setReadOnly(True)
        self.FolderPlace.setObjectName(_fromUtf8("FolderPlace"))
        self.folder.addWidget(self.FolderPlace)
        self.OpenFolderDBox = QtGui.QDialogButtonBox(self.centralwidget)
        self.OpenFolderDBox.setMaximumSize(QtCore.QSize(75, 16777215))
        self.OpenFolderDBox.setOrientation(QtCore.Qt.Horizontal)
        self.OpenFolderDBox.setStandardButtons(QtGui.QDialogButtonBox.Open)
        self.OpenFolderDBox.setCenterButtons(False)
        self.OpenFolderDBox.setObjectName(_fromUtf8("OpenFolderDBox"))
        self.folder.addWidget(self.OpenFolderDBox)
        self.verticalLayout_4.addLayout(self.folder)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.exitbox = QtGui.QDialogButtonBox(self.centralwidget)
        self.exitbox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.RestoreDefaults|QtGui.QDialogButtonBox.Save)
        self.exitbox.setCenterButtons(False)
        self.exitbox.setObjectName(_fromUtf8("exitbox"))
        self.horizontalLayout_2.addWidget(self.exitbox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        Editor.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Editor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 830, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        Editor.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Editor)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Editor.setStatusBar(self.statusbar)

        self.retranslateUi(Editor)
        self.MainTabs.setCurrentIndex(2)
        QtCore.QObject.connect(self.comboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), self.TileImageViewer_2.setText)
        QtCore.QMetaObject.connectSlotsByName(Editor)
        Editor.setTabOrder(self.FolderPlace, self.exitbox)

    def retranslateUi(self, Editor):
        Editor.setWindowTitle(QtGui.QApplication.translate("Editor", "Yukkuri Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Editor", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.EntityMainBox.setTitle(QtGui.QApplication.translate("Editor", "Main", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Editor", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Editor", "Image name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Editor", "Image columns:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Editor", "Image rows:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Editor", "Height:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Editor", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Editor", "Meeting:", None, QtGui.QApplication.UnicodeUTF8))
        self.EntityEntityBox.setTitle(QtGui.QApplication.translate("Editor", "Entity", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Editor", "Damage:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Editor", "Speed:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Editor", "Blood color:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("Editor", "Choose", None, QtGui.QApplication.UnicodeUTF8))
        self.EntityFeedBox.setTitle(QtGui.QApplication.translate("Editor", "Feed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Editor", "Nutritive:", None, QtGui.QApplication.UnicodeUTF8))
        self.EntityMiscBox.setTitle(QtGui.QApplication.translate("Editor", "Misc", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Editor", "Hp:", None, QtGui.QApplication.UnicodeUTF8))
        self.EntityAnimationBox.setTitle(QtGui.QApplication.translate("Editor", "Animation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Editor", "Up:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Editor", "Right-Up:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Editor", "Right:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Editor", "Rigth-Down:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Editor", "Down:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Editor", "Left-Down:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Editor", "Left:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Editor", "Left-Up:", None, QtGui.QApplication.UnicodeUTF8))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.EntityTab), QtGui.QApplication.translate("Editor", "Entity", None, QtGui.QApplication.UnicodeUTF8))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.WidgetsTab), QtGui.QApplication.translate("Editor", "Widgets", None, QtGui.QApplication.UnicodeUTF8))
        self.TilesMainBox.setTitle(QtGui.QApplication.translate("Editor", "Main", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Editor", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Editor", "Image name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Editor", "Offset X:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Editor", "Offset Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Editor", "Blocked:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("Editor", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.MapTilesTab), QtGui.QApplication.translate("Editor", "Tiles", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("Editor", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.MapTab), QtGui.QApplication.translate("Editor", "Map", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Editor", "Source files directory path:", None, QtGui.QApplication.UnicodeUTF8))

