# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Editor.ui'
#
# Created: Thu Sep 29 19:39:58 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Editor(object):
    def setupUi(self, Editor):
        Editor.setObjectName(_fromUtf8("Editor"))
        Editor.resize(821, 755)
        Editor.setWindowTitle(QtGui.QApplication.translate("Editor", "Yukkuri Editor", None, QtGui.QApplication.UnicodeUTF8))
        Editor.setAnimated(True)
        self.centralwidget = QtGui.QWidget(Editor)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.widget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(150, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(230, 16777215))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Editor", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.FilesList = QtGui.QListWidget(self.groupBox_2)
        self.FilesList.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.FilesList.setObjectName(_fromUtf8("FilesList"))
        self.verticalLayout_8.addWidget(self.FilesList)
        self.NewConfigButton = QtGui.QPushButton(self.groupBox_2)
        self.NewConfigButton.setText(QtGui.QApplication.translate("Editor", "New config file", None, QtGui.QApplication.UnicodeUTF8))
        self.NewConfigButton.setObjectName(_fromUtf8("NewConfigButton"))
        self.verticalLayout_8.addWidget(self.NewConfigButton)
        self.ItemsList = QtGui.QListWidget(self.groupBox_2)
        self.ItemsList.setObjectName(_fromUtf8("ItemsList"))
        self.verticalLayout_8.addWidget(self.ItemsList)
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_2.setText(QtGui.QApplication.translate("Editor", "New entry", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout_8.addWidget(self.pushButton_2)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.MainTabs = QtGui.QTabWidget(self.widget)
        self.MainTabs.setObjectName(_fromUtf8("MainTabs"))
        self.SpriteTab = QtGui.QWidget()
        self.SpriteTab.setObjectName(_fromUtf8("SpriteTab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.SpriteTab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.SpritesMainBox = QtGui.QGroupBox(self.SpriteTab)
        self.SpritesMainBox.setMaximumSize(QtCore.QSize(350, 16777215))
        self.SpritesMainBox.setTitle(QtGui.QApplication.translate("Editor", "Main", None, QtGui.QApplication.UnicodeUTF8))
        self.SpritesMainBox.setObjectName(_fromUtf8("SpritesMainBox"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.SpritesMainBox)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.ID_6 = YReadOnlySimpleInputWidget(self.SpritesMainBox)
        self.ID_6.setEnabled(True)
        self.ID_6.setObjectName(_fromUtf8("ID_6"))
        self.verticalLayout_16.addWidget(self.ID_6)
        self.Name_4 = YSimpleInputWidget(self.SpritesMainBox)
        self.Name_4.setEnabled(True)
        self.Name_4.setObjectName(_fromUtf8("Name_4"))
        self.verticalLayout_16.addWidget(self.Name_4)
        self.Image_5 = QtGui.QWidget(self.SpritesMainBox)
        self.Image_5.setObjectName(_fromUtf8("Image_5"))
        self.Image_6 = QtGui.QHBoxLayout(self.Image_5)
        self.Image_6.setMargin(0)
        self.Image_6.setMargin(0)
        self.Image_6.setObjectName(_fromUtf8("Image_6"))
        self.label_7 = QtGui.QLabel(self.Image_5)
        self.label_7.setText(QtGui.QApplication.translate("Editor", "Image:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.Image_6.addWidget(self.label_7)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Image_6.addItem(spacerItem)
        self.lineEdit_36 = QtGui.QLineEdit(self.Image_5)
        self.lineEdit_36.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_36.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_36.setObjectName(_fromUtf8("lineEdit_36"))
        self.Image_6.addWidget(self.lineEdit_36)
        self.dialogButtonBox_2 = QtGui.QDialogButtonBox(self.Image_5)
        self.dialogButtonBox_2.setMaximumSize(QtCore.QSize(75, 16777215))
        self.dialogButtonBox_2.setStandardButtons(QtGui.QDialogButtonBox.Open)
        self.dialogButtonBox_2.setObjectName(_fromUtf8("dialogButtonBox_2"))
        self.Image_6.addWidget(self.dialogButtonBox_2)
        self.verticalLayout_16.addWidget(self.Image_5)
        self.Width_2 = YSpinBoxInputWidget(self.SpritesMainBox)
        self.Width_2.setObjectName(_fromUtf8("Width_2"))
        self.verticalLayout_16.addWidget(self.Width_2)
        self.Height_2 = YSpinBoxInputWidget(self.SpritesMainBox)
        self.Height_2.setObjectName(_fromUtf8("Height_2"))
        self.verticalLayout_16.addWidget(self.Height_2)
        self.OffsetX_2 = YSpinBoxInputWidget(self.SpritesMainBox)
        self.OffsetX_2.setObjectName(_fromUtf8("OffsetX_2"))
        self.verticalLayout_16.addWidget(self.OffsetX_2)
        self.OffsetY_2 = YSpinBoxInputWidget(self.SpritesMainBox)
        self.OffsetY_2.setObjectName(_fromUtf8("OffsetY_2"))
        self.verticalLayout_16.addWidget(self.OffsetY_2)
        self.Imagerows_2 = YSpinBoxInputWidget(self.SpritesMainBox)
        self.Imagerows_2.setObjectName(_fromUtf8("Imagerows_2"))
        self.verticalLayout_16.addWidget(self.Imagerows_2)
        self.Imagecols_2 = YSpinBoxInputWidget(self.SpritesMainBox)
        self.Imagecols_2.setObjectName(_fromUtf8("Imagecols_2"))
        self.verticalLayout_16.addWidget(self.Imagecols_2)
        self.gridLayout_3.addWidget(self.SpritesMainBox, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        self.groupBox_9 = QtGui.QGroupBox(self.SpriteTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setTitle(QtGui.QApplication.translate("Editor", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.TileImageViewer_2 = QtGui.QLabel(self.groupBox_9)
        self.TileImageViewer_2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TileImageViewer_2.sizePolicy().hasHeightForWidth())
        self.TileImageViewer_2.setSizePolicy(sizePolicy)
        self.TileImageViewer_2.setMinimumSize(QtCore.QSize(64, 64))
        self.TileImageViewer_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.TileImageViewer_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.TileImageViewer_2.setStyleSheet(_fromUtf8("QLabel {\n"
"    padding: 1px;\n"
"}"))
        self.TileImageViewer_2.setFrameShape(QtGui.QFrame.Box)
        self.TileImageViewer_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.TileImageViewer_2.setLineWidth(1)
        self.TileImageViewer_2.setMidLineWidth(0)
        self.TileImageViewer_2.setText(_fromUtf8(""))
        self.TileImageViewer_2.setTextFormat(QtCore.Qt.AutoText)
        self.TileImageViewer_2.setScaledContents(False)
        self.TileImageViewer_2.setAlignment(QtCore.Qt.AlignCenter)
        self.TileImageViewer_2.setWordWrap(False)
        self.TileImageViewer_2.setIndent(0)
        self.TileImageViewer_2.setOpenExternalLinks(False)
        self.TileImageViewer_2.setObjectName(_fromUtf8("TileImageViewer_2"))
        self.horizontalLayout_7.addWidget(self.TileImageViewer_2)
        self.gridLayout_3.addWidget(self.groupBox_9, 0, 1, 1, 1)
        self.MainTabs.addTab(self.SpriteTab, _fromUtf8(""))
        self.EntityTab = QtGui.QWidget()
        self.EntityTab.setObjectName(_fromUtf8("EntityTab"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.EntityTab)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.EntityMainBox = QtGui.QGroupBox(self.EntityTab)
        self.EntityMainBox.setTitle(QtGui.QApplication.translate("Editor", "Main", None, QtGui.QApplication.UnicodeUTF8))
        self.EntityMainBox.setObjectName(_fromUtf8("EntityMainBox"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.EntityMainBox)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.ID = YReadOnlySimpleInputWidget(self.EntityMainBox)
        self.ID.setEnabled(True)
        self.ID.setObjectName(_fromUtf8("ID"))
        self.verticalLayout_7.addWidget(self.ID)
        self.Name = YSimpleInputWidget(self.EntityMainBox)
        self.Name.setEnabled(True)
        self.Name.setObjectName(_fromUtf8("Name"))
        self.verticalLayout_7.addWidget(self.Name)
        self.Image_3 = QtGui.QWidget(self.EntityMainBox)
        self.Image_3.setObjectName(_fromUtf8("Image_3"))
        self.Image = QtGui.QHBoxLayout(self.Image_3)
        self.Image.setMargin(0)
        self.Image.setMargin(0)
        self.Image.setObjectName(_fromUtf8("Image"))
        self.label_2 = QtGui.QLabel(self.Image_3)
        self.label_2.setText(QtGui.QApplication.translate("Editor", "Image:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.Image.addWidget(self.label_2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Image.addItem(spacerItem2)
        self.EntityImgField = QtGui.QLineEdit(self.Image_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EntityImgField.sizePolicy().hasHeightForWidth())
        self.EntityImgField.setSizePolicy(sizePolicy)
        self.EntityImgField.setMinimumSize(QtCore.QSize(0, 0))
        self.EntityImgField.setMaximumSize(QtCore.QSize(111, 16777215))
        self.EntityImgField.setObjectName(_fromUtf8("EntityImgField"))
        self.Image.addWidget(self.EntityImgField)
        self.ImageChooseButton_2 = QtGui.QPushButton(self.Image_3)
        self.ImageChooseButton_2.setText(QtGui.QApplication.translate("Editor", "Choose", None, QtGui.QApplication.UnicodeUTF8))
        self.ImageChooseButton_2.setAutoDefault(False)
        self.ImageChooseButton_2.setDefault(False)
        self.ImageChooseButton_2.setFlat(False)
        self.ImageChooseButton_2.setObjectName(_fromUtf8("ImageChooseButton_2"))
        self.Image.addWidget(self.ImageChooseButton_2)
        self.verticalLayout_7.addWidget(self.Image_3)
        self.Height = QtGui.QWidget(self.EntityMainBox)
        self.Height.setObjectName(_fromUtf8("Height"))
        self.imgcols_9 = QtGui.QHBoxLayout(self.Height)
        self.imgcols_9.setMargin(0)
        self.imgcols_9.setMargin(0)
        self.imgcols_9.setObjectName(_fromUtf8("imgcols_9"))
        self.label_38 = QtGui.QLabel(self.Height)
        self.label_38.setText(QtGui.QApplication.translate("Editor", "Height:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.imgcols_9.addWidget(self.label_38)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.imgcols_9.addItem(spacerItem3)
        self.spinBox_9 = QtGui.QSpinBox(self.Height)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_9.sizePolicy().hasHeightForWidth())
        self.spinBox_9.setSizePolicy(sizePolicy)
        self.spinBox_9.setMinimumSize(QtCore.QSize(120, 0))
        self.spinBox_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_9.setMaximum(999999999)
        self.spinBox_9.setObjectName(_fromUtf8("spinBox_9"))
        self.imgcols_9.addWidget(self.spinBox_9)
        self.Multipler_18 = QtGui.QWidget(self.Height)
        self.Multipler_18.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Multipler_18.setObjectName(_fromUtf8("Multipler_18"))
        self.horizontalLayout_64 = QtGui.QHBoxLayout(self.Multipler_18)
        self.horizontalLayout_64.setMargin(0)
        self.horizontalLayout_64.setMargin(0)
        self.horizontalLayout_64.setObjectName(_fromUtf8("horizontalLayout_64"))
        self.label_117 = QtGui.QLabel(self.Multipler_18)
        self.label_117.setText(QtGui.QApplication.translate("Editor", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_117.setObjectName(_fromUtf8("label_117"))
        self.horizontalLayout_64.addWidget(self.label_117)
        self.spinBox_91 = QtGui.QSpinBox(self.Multipler_18)
        self.spinBox_91.setMaximumSize(QtCore.QSize(48, 16777215))
        self.spinBox_91.setMinimum(1)
        self.spinBox_91.setMaximum(999)
        self.spinBox_91.setObjectName(_fromUtf8("spinBox_91"))
        self.horizontalLayout_64.addWidget(self.spinBox_91)
        self.imgcols_9.addWidget(self.Multipler_18)
        self.verticalLayout_7.addWidget(self.Height)
        self.Width = QtGui.QWidget(self.EntityMainBox)
        self.Width.setObjectName(_fromUtf8("Width"))
        self.imgcols_10 = QtGui.QHBoxLayout(self.Width)
        self.imgcols_10.setMargin(0)
        self.imgcols_10.setMargin(0)
        self.imgcols_10.setObjectName(_fromUtf8("imgcols_10"))
        self.label_39 = QtGui.QLabel(self.Width)
        self.label_39.setText(QtGui.QApplication.translate("Editor", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.imgcols_10.addWidget(self.label_39)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.imgcols_10.addItem(spacerItem4)
        self.spinBox_10 = QtGui.QSpinBox(self.Width)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_10.sizePolicy().hasHeightForWidth())
        self.spinBox_10.setSizePolicy(sizePolicy)
        self.spinBox_10.setMinimumSize(QtCore.QSize(120, 0))
        self.spinBox_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_10.setMaximum(999999999)
        self.spinBox_10.setObjectName(_fromUtf8("spinBox_10"))
        self.imgcols_10.addWidget(self.spinBox_10)
        self.Multipler_19 = QtGui.QWidget(self.Width)
        self.Multipler_19.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Multipler_19.setObjectName(_fromUtf8("Multipler_19"))
        self.horizontalLayout_66 = QtGui.QHBoxLayout(self.Multipler_19)
        self.horizontalLayout_66.setMargin(0)
        self.horizontalLayout_66.setMargin(0)
        self.horizontalLayout_66.setObjectName(_fromUtf8("horizontalLayout_66"))
        self.label_119 = QtGui.QLabel(self.Multipler_19)
        self.label_119.setText(QtGui.QApplication.translate("Editor", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_119.setObjectName(_fromUtf8("label_119"))
        self.horizontalLayout_66.addWidget(self.label_119)
        self.spinBox_93 = QtGui.QSpinBox(self.Multipler_19)
        self.spinBox_93.setMaximumSize(QtCore.QSize(48, 16777215))
        self.spinBox_93.setMinimum(1)
        self.spinBox_93.setMaximum(999)
        self.spinBox_93.setObjectName(_fromUtf8("spinBox_93"))
        self.horizontalLayout_66.addWidget(self.spinBox_93)
        self.imgcols_10.addWidget(self.Multipler_19)
        self.verticalLayout_7.addWidget(self.Width)
        self.Meeting = QtGui.QWidget(self.EntityMainBox)
        self.Meeting.setObjectName(_fromUtf8("Meeting"))
        self.imgcols_11 = QtGui.QHBoxLayout(self.Meeting)
        self.imgcols_11.setMargin(0)
        self.imgcols_11.setMargin(0)
        self.imgcols_11.setObjectName(_fromUtf8("imgcols_11"))
        self.label_40 = QtGui.QLabel(self.Meeting)
        self.label_40.setText(QtGui.QApplication.translate("Editor", "Meeting:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.imgcols_11.addWidget(self.label_40)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.imgcols_11.addItem(spacerItem5)
        self.doubleSpinBox_11 = QtGui.QDoubleSpinBox(self.Meeting)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_11.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_11.setSizePolicy(sizePolicy)
        self.doubleSpinBox_11.setMinimumSize(QtCore.QSize(120, 0))
        self.doubleSpinBox_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_11.setObjectName(_fromUtf8("doubleSpinBox_11"))
        self.imgcols_11.addWidget(self.doubleSpinBox_11)
        self.Multipler_20 = QtGui.QWidget(self.Meeting)
        self.Multipler_20.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Multipler_20.setObjectName(_fromUtf8("Multipler_20"))
        self.horizontalLayout_67 = QtGui.QHBoxLayout(self.Multipler_20)
        self.horizontalLayout_67.setMargin(0)
        self.horizontalLayout_67.setMargin(0)
        self.horizontalLayout_67.setObjectName(_fromUtf8("horizontalLayout_67"))
        self.label_120 = QtGui.QLabel(self.Multipler_20)
        self.label_120.setText(QtGui.QApplication.translate("Editor", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_120.setObjectName(_fromUtf8("label_120"))
        self.horizontalLayout_67.addWidget(self.label_120)
        self.spinBox_94 = QtGui.QSpinBox(self.Multipler_20)
        self.spinBox_94.setMaximumSize(QtCore.QSize(48, 16777215))
        self.spinBox_94.setMinimum(1)
        self.spinBox_94.setMaximum(999)
        self.spinBox_94.setObjectName(_fromUtf8("spinBox_94"))
        self.horizontalLayout_67.addWidget(self.spinBox_94)
        self.imgcols_11.addWidget(self.Multipler_20)
        self.verticalLayout_7.addWidget(self.Meeting)
        self.verticalLayout_10.addWidget(self.EntityMainBox)
        self.EntityEntityBox = QtGui.QGroupBox(self.EntityTab)
        self.EntityEntityBox.setTitle(QtGui.QApplication.translate("Editor", "Entity", None, QtGui.QApplication.UnicodeUTF8))
        self.EntityEntityBox.setObjectName(_fromUtf8("EntityEntityBox"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.EntityEntityBox)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.Damage = QtGui.QWidget(self.EntityEntityBox)
        self.Damage.setObjectName(_fromUtf8("Damage"))
        self.imgcols_12 = QtGui.QHBoxLayout(self.Damage)
        self.imgcols_12.setMargin(0)
        self.imgcols_12.setMargin(0)
        self.imgcols_12.setObjectName(_fromUtf8("imgcols_12"))
        self.label_41 = QtGui.QLabel(self.Damage)
        self.label_41.setText(QtGui.QApplication.translate("Editor", "Damage:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.imgcols_12.addWidget(self.label_41)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.imgcols_12.addItem(spacerItem6)
        self.doubleSpinBox_12 = QtGui.QDoubleSpinBox(self.Damage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_12.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_12.setSizePolicy(sizePolicy)
        self.doubleSpinBox_12.setMinimumSize(QtCore.QSize(120, 0))
        self.doubleSpinBox_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_12.setObjectName(_fromUtf8("doubleSpinBox_12"))
        self.imgcols_12.addWidget(self.doubleSpinBox_12)
        self.Multipler_14 = QtGui.QWidget(self.Damage)
        self.Multipler_14.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Multipler_14.setObjectName(_fromUtf8("Multipler_14"))
        self.horizontalLayout_56 = QtGui.QHBoxLayout(self.Multipler_14)
        self.horizontalLayout_56.setMargin(0)
        self.horizontalLayout_56.setMargin(0)
        self.horizontalLayout_56.setObjectName(_fromUtf8("horizontalLayout_56"))
        self.label_109 = QtGui.QLabel(self.Multipler_14)
        self.label_109.setText(QtGui.QApplication.translate("Editor", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_109.setObjectName(_fromUtf8("label_109"))
        self.horizontalLayout_56.addWidget(self.label_109)
        self.spinBox_83 = QtGui.QSpinBox(self.Multipler_14)
        self.spinBox_83.setMaximumSize(QtCore.QSize(48, 16777215))
        self.spinBox_83.setMinimum(1)
        self.spinBox_83.setMaximum(999)
        self.spinBox_83.setObjectName(_fromUtf8("spinBox_83"))
        self.horizontalLayout_56.addWidget(self.spinBox_83)
        self.imgcols_12.addWidget(self.Multipler_14)
        self.verticalLayout_12.addWidget(self.Damage)
        self.Speed = QtGui.QWidget(self.EntityEntityBox)
        self.Speed.setObjectName(_fromUtf8("Speed"))
        self.imgcols_13 = QtGui.QHBoxLayout(self.Speed)
        self.imgcols_13.setMargin(0)
        self.imgcols_13.setMargin(0)
        self.imgcols_13.setObjectName(_fromUtf8("imgcols_13"))
        self.label_42 = QtGui.QLabel(self.Speed)
        self.label_42.setText(QtGui.QApplication.translate("Editor", "Speed:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.imgcols_13.addWidget(self.label_42)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.imgcols_13.addItem(spacerItem7)
        self.doubleSpinBox_16 = QtGui.QDoubleSpinBox(self.Speed)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_16.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_16.setSizePolicy(sizePolicy)
        self.doubleSpinBox_16.setMinimumSize(QtCore.QSize(120, 0))
        self.doubleSpinBox_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_16.setObjectName(_fromUtf8("doubleSpinBox_16"))
        self.imgcols_13.addWidget(self.doubleSpinBox_16)
        self.Multipler_15 = QtGui.QWidget(self.Speed)
        self.Multipler_15.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Multipler_15.setObjectName(_fromUtf8("Multipler_15"))
        self.horizontalLayout_58 = QtGui.QHBoxLayout(self.Multipler_15)
        self.horizontalLayout_58.setMargin(0)
        self.horizontalLayout_58.setMargin(0)
        self.horizontalLayout_58.setObjectName(_fromUtf8("horizontalLayout_58"))
        self.label_111 = QtGui.QLabel(self.Multipler_15)
        self.label_111.setText(QtGui.QApplication.translate("Editor", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_111.setObjectName(_fromUtf8("label_111"))
        self.horizontalLayout_58.addWidget(self.label_111)
        self.spinBox_85 = QtGui.QSpinBox(self.Multipler_15)
        self.spinBox_85.setMaximumSize(QtCore.QSize(48, 16777215))
        self.spinBox_85.setMinimum(1)
        self.spinBox_85.setMaximum(999)
        self.spinBox_85.setObjectName(_fromUtf8("spinBox_85"))
        self.horizontalLayout_58.addWidget(self.spinBox_85)
        self.imgcols_13.addWidget(self.Multipler_15)
        self.verticalLayout_12.addWidget(self.Speed)
        self.Bloodcolor = QtGui.QWidget(self.EntityEntityBox)
        self.Bloodcolor.setObjectName(_fromUtf8("Bloodcolor"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.Bloodcolor)
        self.horizontalLayout_20.setMargin(0)
        self.horizontalLayout_20.setMargin(0)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_14 = QtGui.QLabel(self.Bloodcolor)
        self.label_14.setText(QtGui.QApplication.translate("Editor", "Blood color:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_20.addWidget(self.label_14)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem8)
        self.spinBox_13 = QtGui.QSpinBox(self.Bloodcolor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_13.sizePolicy().hasHeightForWidth())
        self.spinBox_13.setSizePolicy(sizePolicy)
        self.spinBox_13.setMaximumSize(QtCore.QSize(38, 16777215))
        self.spinBox_13.setFrame(True)
        self.spinBox_13.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_13.setKeyboardTracking(False)
        self.spinBox_13.setMaximum(256)
        self.spinBox_13.setObjectName(_fromUtf8("spinBox_13"))
        self.horizontalLayout_20.addWidget(self.spinBox_13)
        self.spinBox_14 = QtGui.QSpinBox(self.Bloodcolor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_14.sizePolicy().hasHeightForWidth())
        self.spinBox_14.setSizePolicy(sizePolicy)
        self.spinBox_14.setMaximumSize(QtCore.QSize(38, 16777215))
        self.spinBox_14.setFrame(True)
        self.spinBox_14.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_14.setKeyboardTracking(False)
        self.spinBox_14.setMaximum(256)
        self.spinBox_14.setObjectName(_fromUtf8("spinBox_14"))
        self.horizontalLayout_20.addWidget(self.spinBox_14)
        self.spinBox_15 = QtGui.QSpinBox(self.Bloodcolor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_15.sizePolicy().hasHeightForWidth())
        self.spinBox_15.setSizePolicy(sizePolicy)
        self.spinBox_15.setMaximumSize(QtCore.QSize(38, 16777215))
        self.spinBox_15.setFrame(True)
        self.spinBox_15.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_15.setKeyboardTracking(False)
        self.spinBox_15.setMaximum(256)
        self.spinBox_15.setObjectName(_fromUtf8("spinBox_15"))
        self.horizontalLayout_20.addWidget(self.spinBox_15)
        self.toolButton = QtGui.QToolButton(self.Bloodcolor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setText(QtGui.QApplication.translate("Editor", "Choose", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout_20.addWidget(self.toolButton)
        self.verticalLayout_12.addWidget(self.Bloodcolor)
        self.verticalLayout_10.addWidget(self.EntityEntityBox)
        self.EntityFeedBox = QtGui.QGroupBox(self.EntityTab)
        self.EntityFeedBox.setTitle(QtGui.QApplication.translate("Editor", "Feed", None, QtGui.QApplication.UnicodeUTF8))
        self.EntityFeedBox.setObjectName(_fromUtf8("EntityFeedBox"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.EntityFeedBox)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.Nutritive = QtGui.QWidget(self.EntityFeedBox)
        self.Nutritive.setObjectName(_fromUtf8("Nutritive"))
        self.imgcols_14 = QtGui.QHBoxLayout(self.Nutritive)
        self.imgcols_14.setMargin(0)
        self.imgcols_14.setMargin(0)
        self.imgcols_14.setObjectName(_fromUtf8("imgcols_14"))
        self.label_43 = QtGui.QLabel(self.Nutritive)
        self.label_43.setText(QtGui.QApplication.translate("Editor", "Nutritive:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.imgcols_14.addWidget(self.label_43)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.imgcols_14.addItem(spacerItem9)
        self.doubleSpinBox_17 = QtGui.QDoubleSpinBox(self.Nutritive)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_17.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_17.setSizePolicy(sizePolicy)
        self.doubleSpinBox_17.setMinimumSize(QtCore.QSize(120, 0))
        self.doubleSpinBox_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_17.setObjectName(_fromUtf8("doubleSpinBox_17"))
        self.imgcols_14.addWidget(self.doubleSpinBox_17)
        self.Multipler_16 = QtGui.QWidget(self.Nutritive)
        self.Multipler_16.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Multipler_16.setObjectName(_fromUtf8("Multipler_16"))
        self.horizontalLayout_59 = QtGui.QHBoxLayout(self.Multipler_16)
        self.horizontalLayout_59.setMargin(0)
        self.horizontalLayout_59.setMargin(0)
        self.horizontalLayout_59.setObjectName(_fromUtf8("horizontalLayout_59"))
        self.label_112 = QtGui.QLabel(self.Multipler_16)
        self.label_112.setText(QtGui.QApplication.translate("Editor", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_112.setObjectName(_fromUtf8("label_112"))
        self.horizontalLayout_59.addWidget(self.label_112)
        self.spinBox_86 = QtGui.QSpinBox(self.Multipler_16)
        self.spinBox_86.setMaximumSize(QtCore.QSize(48, 16777215))
        self.spinBox_86.setMinimum(1)
        self.spinBox_86.setMaximum(999)
        self.spinBox_86.setObjectName(_fromUtf8("spinBox_86"))
        self.horizontalLayout_59.addWidget(self.spinBox_86)
        self.imgcols_14.addWidget(self.Multipler_16)
        self.verticalLayout_11.addWidget(self.Nutritive)
        self.verticalLayout_10.addWidget(self.EntityFeedBox)
        self.EntityMiscBox = QtGui.QGroupBox(self.EntityTab)
        self.EntityMiscBox.setTitle(QtGui.QApplication.translate("Editor", "Misc", None, QtGui.QApplication.UnicodeUTF8))
        self.EntityMiscBox.setObjectName(_fromUtf8("EntityMiscBox"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.EntityMiscBox)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.Hp = QtGui.QWidget(self.EntityMiscBox)
        self.Hp.setObjectName(_fromUtf8("Hp"))
        self.imgcols_15 = QtGui.QHBoxLayout(self.Hp)
        self.imgcols_15.setMargin(0)
        self.imgcols_15.setMargin(0)
        self.imgcols_15.setObjectName(_fromUtf8("imgcols_15"))
        self.label_44 = QtGui.QLabel(self.Hp)
        self.label_44.setText(QtGui.QApplication.translate("Editor", "Hp:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.imgcols_15.addWidget(self.label_44)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.imgcols_15.addItem(spacerItem10)
        self.doubleSpinBox_18 = QtGui.QDoubleSpinBox(self.Hp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_18.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_18.setSizePolicy(sizePolicy)
        self.doubleSpinBox_18.setMinimumSize(QtCore.QSize(120, 0))
        self.doubleSpinBox_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_18.setObjectName(_fromUtf8("doubleSpinBox_18"))
        self.imgcols_15.addWidget(self.doubleSpinBox_18)
        self.Multipler_17 = QtGui.QWidget(self.Hp)
        self.Multipler_17.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Multipler_17.setObjectName(_fromUtf8("Multipler_17"))
        self.horizontalLayout_63 = QtGui.QHBoxLayout(self.Multipler_17)
        self.horizontalLayout_63.setMargin(0)
        self.horizontalLayout_63.setMargin(0)
        self.horizontalLayout_63.setObjectName(_fromUtf8("horizontalLayout_63"))
        self.label_116 = QtGui.QLabel(self.Multipler_17)
        self.label_116.setText(QtGui.QApplication.translate("Editor", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_116.setObjectName(_fromUtf8("label_116"))
        self.horizontalLayout_63.addWidget(self.label_116)
        self.spinBox_90 = QtGui.QSpinBox(self.Multipler_17)
        self.spinBox_90.setMaximumSize(QtCore.QSize(48, 16777215))
        self.spinBox_90.setMinimum(1)
        self.spinBox_90.setMaximum(999)
        self.spinBox_90.setObjectName(_fromUtf8("spinBox_90"))
        self.horizontalLayout_63.addWidget(self.spinBox_90)
        self.imgcols_15.addWidget(self.Multipler_17)
        self.verticalLayout_13.addWidget(self.Hp)
        self.verticalLayout_10.addWidget(self.EntityMiscBox)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem11)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.EntityAnimationBox = QtGui.QGroupBox(self.EntityTab)
        self.EntityAnimationBox.setTitle(QtGui.QApplication.translate("Editor", "Animation", None, QtGui.QApplication.UnicodeUTF8))
        self.EntityAnimationBox.setObjectName(_fromUtf8("EntityAnimationBox"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.EntityAnimationBox)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.Up = QtGui.QWidget(self.EntityAnimationBox)
        self.Up.setObjectName(_fromUtf8("Up"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.Up)
        self.horizontalLayout_15.setMargin(0)
        self.horizontalLayout_15.setMargin(0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_9 = QtGui.QLabel(self.Up)
        self.label_9.setText(QtGui.QApplication.translate("Editor", "Up:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_15.addWidget(self.label_9)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem12)
        self.spinBox_3 = QtGui.QSpinBox(self.Up)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_3.sizePolicy().hasHeightForWidth())
        self.spinBox_3.setSizePolicy(sizePolicy)
        self.spinBox_3.setMinimumSize(QtCore.QSize(80, 0))
        self.spinBox_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBox_3.setFrame(True)
        self.spinBox_3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_3.setMaximum(999)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.horizontalLayout_15.addWidget(self.spinBox_3)
        self.spinBox_5 = QtGui.QSpinBox(self.Up)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_5.sizePolicy().hasHeightForWidth())
        self.spinBox_5.setSizePolicy(sizePolicy)
        self.spinBox_5.setMinimumSize(QtCore.QSize(80, 0))
        self.spinBox_5.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBox_5.setFrame(True)
        self.spinBox_5.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_5.setMaximum(999)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.horizontalLayout_15.addWidget(self.spinBox_5)
        self.verticalLayout_9.addWidget(self.Up)
        self.Rightup = QtGui.QWidget(self.EntityAnimationBox)
        self.Rightup.setObjectName(_fromUtf8("Rightup"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout(self.Rightup)
        self.horizontalLayout_27.setMargin(0)
        self.horizontalLayout_27.setMargin(0)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_21 = QtGui.QLabel(self.Rightup)
        self.label_21.setText(QtGui.QApplication.translate("Editor", "Right-Up:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_27.addWidget(self.label_21)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem13)
        self.spinBox_6 = QtGui.QSpinBox(self.Rightup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_6.sizePolicy().hasHeightForWidth())
        self.spinBox_6.setSizePolicy(sizePolicy)
        self.spinBox_6.setMinimumSize(QtCore.QSize(80, 0))
        self.spinBox_6.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBox_6.setFrame(True)
        self.spinBox_6.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_6.setMaximum(999)
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.horizontalLayout_27.addWidget(self.spinBox_6)
        self.spinBox_19 = QtGui.QSpinBox(self.Rightup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_19.sizePolicy().hasHeightForWidth())
        self.spinBox_19.setSizePolicy(sizePolicy)
        self.spinBox_19.setMinimumSize(QtCore.QSize(80, 0))
        self.spinBox_19.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBox_19.setFrame(True)
        self.spinBox_19.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_19.setMaximum(999)
        self.spinBox_19.setObjectName(_fromUtf8("spinBox_19"))
        self.horizontalLayout_27.addWidget(self.spinBox_19)
        self.verticalLayout_9.addWidget(self.Rightup)
        self.Right = QtGui.QWidget(self.EntityAnimationBox)
        self.Right.setObjectName(_fromUtf8("Right"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.Right)
        self.horizontalLayout_22.setMargin(0)
        self.horizontalLayout_22.setMargin(0)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_16 = QtGui.QLabel(self.Right)
        self.label_16.setText(QtGui.QApplication.translate("Editor", "Right:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_22.addWidget(self.label_16)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem14)
        self.spinBox_21 = QtGui.QSpinBox(self.Right)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_21.sizePolicy().hasHeightForWidth())
        self.spinBox_21.setSizePolicy(sizePolicy)
        self.spinBox_21.setMinimumSize(QtCore.QSize(80, 0))
        self.spinBox_21.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBox_21.setFrame(True)
        self.spinBox_21.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_21.setMaximum(999)
        self.spinBox_21.setObjectName(_fromUtf8("spinBox_21"))
        self.horizontalLayout_22.addWidget(self.spinBox_21)
        self.spinBox_20 = QtGui.QSpinBox(self.Right)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_20.sizePolicy().hasHeightForWidth())
        self.spinBox_20.setSizePolicy(sizePolicy)
        self.spinBox_20.setMinimumSize(QtCore.QSize(80, 0))
        self.spinBox_20.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBox_20.setFrame(True)
        self.spinBox_20.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_20.setMaximum(999)
        self.spinBox_20.setObjectName(_fromUtf8("spinBox_20"))
        self.horizontalLayout_22.addWidget(self.spinBox_20)
        self.verticalLayout_9.addWidget(self.Right)
        self.Rightdown = QtGui.QWidget(self.EntityAnimationBox)
        self.Rightdown.setObjectName(_fromUtf8("Rightdown"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout(self.Rightdown)
        self.horizontalLayout_28.setMargin(0)
        self.horizontalLayout_28.setMargin(0)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_22 = QtGui.QLabel(self.Rightdown)
        self.label_22.setText(QtGui.QApplication.translate("Editor", "Rigth-Down:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_28.addWidget(self.label_22)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem15)
        self.spinBox_22 = QtGui.QSpinBox(self.Rightdown)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_22.sizePolicy().hasHeightForWidth())
        self.spinBox_22.setSizePolicy(sizePolicy)
        self.spinBox_22.setMinimumSize(QtCore.QSize(80, 0))
        self.spinBox_22.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBox_22.setFrame(True)
        self.spinBox_22.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_22.setMaximum(999)
        self.spinBox_22.setObjectName(_fromUtf8("spinBox_22"))
        self.horizontalLayout_28.addWidget(self.spinBox_22)
        self.spinBox_23 = QtGui.QSpinBox(self.Rightdown)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_23.sizePolicy().hasHeightForWidth())
        self.spinBox_23.setSizePolicy(sizePolicy)
        self.spinBox_23.setMinimumSize(QtCore.QSize(80, 0))
        self.spinBox_23.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBox_23.setFrame(True)
        self.spinBox_23.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_23.setMaximum(999)
        self.spinBox_23.setObjectName(_fromUtf8("spinBox_23"))
        self.horizontalLayout_28.addWidget(self.spinBox_23)
        self.verticalLayout_9.addWidget(self.Rightdown)
        self.Down = QtGui.QWidget(self.EntityAnimationBox)
        self.Down.setObjectName(_fromUtf8("Down"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.Down)
        self.horizontalLayout_29.setMargin(0)
        self.horizontalLayout_29.setMargin(0)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.label_23 = QtGui.QLabel(self.Down)
        self.label_23.setText(QtGui.QApplication.translate("Editor", "Down:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_29.addWidget(self.label_23)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem16)
        self.spinBox_25 = QtGui.QSpinBox(self.Down)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_25.sizePolicy().hasHeightForWidth())
        self.spinBox_25.setSizePolicy(sizePolicy)
        self.spinBox_25.setMinimumSize(QtCore.QSize(80, 0))
        self.spinBox_25.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBox_25.setFrame(True)
        self.spinBox_25.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_25.setMaximum(999)
        self.spinBox_25.setObjectName(_fromUtf8("spinBox_25"))
        self.horizontalLayout_29.addWidget(self.spinBox_25)
        self.spinBox_24 = QtGui.QSpinBox(self.Down)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_24.sizePolicy().hasHeightForWidth())
        self.spinBox_24.setSizePolicy(sizePolicy)
        self.spinBox_24.setMinimumSize(QtCore.QSize(80, 0))
        self.spinBox_24.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBox_24.setFrame(True)
        self.spinBox_24.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_24.setMaximum(999)
        self.spinBox_24.setObjectName(_fromUtf8("spinBox_24"))
        self.horizontalLayout_29.addWidget(self.spinBox_24)
        self.verticalLayout_9.addWidget(self.Down)
        self.Leftdown = QtGui.QWidget(self.EntityAnimationBox)
        self.Leftdown.setObjectName(_fromUtf8("Leftdown"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.Leftdown)
        self.horizontalLayout_21.setMargin(0)
        self.horizontalLayout_21.setMargin(0)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_15 = QtGui.QLabel(self.Leftdown)
        self.label_15.setText(QtGui.QApplication.translate("Editor", "Left-Down:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_21.addWidget(self.label_15)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem17)
        self.spinBox_27 = QtGui.QSpinBox(self.Leftdown)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_27.sizePolicy().hasHeightForWidth())
        self.spinBox_27.setSizePolicy(sizePolicy)
        self.spinBox_27.setMinimumSize(QtCore.QSize(80, 0))
        self.spinBox_27.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBox_27.setFrame(True)
        self.spinBox_27.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_27.setMaximum(999)
        self.spinBox_27.setObjectName(_fromUtf8("spinBox_27"))
        self.horizontalLayout_21.addWidget(self.spinBox_27)
        self.spinBox_26 = QtGui.QSpinBox(self.Leftdown)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_26.sizePolicy().hasHeightForWidth())
        self.spinBox_26.setSizePolicy(sizePolicy)
        self.spinBox_26.setMinimumSize(QtCore.QSize(80, 0))
        self.spinBox_26.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBox_26.setFrame(True)
        self.spinBox_26.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_26.setMaximum(999)
        self.spinBox_26.setObjectName(_fromUtf8("spinBox_26"))
        self.horizontalLayout_21.addWidget(self.spinBox_26)
        self.verticalLayout_9.addWidget(self.Leftdown)
        self.Left = QtGui.QWidget(self.EntityAnimationBox)
        self.Left.setObjectName(_fromUtf8("Left"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.Left)
        self.horizontalLayout_24.setMargin(0)
        self.horizontalLayout_24.setMargin(0)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_18 = QtGui.QLabel(self.Left)
        self.label_18.setText(QtGui.QApplication.translate("Editor", "Left:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_24.addWidget(self.label_18)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem18)
        self.spinBox_29 = QtGui.QSpinBox(self.Left)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_29.sizePolicy().hasHeightForWidth())
        self.spinBox_29.setSizePolicy(sizePolicy)
        self.spinBox_29.setMinimumSize(QtCore.QSize(80, 0))
        self.spinBox_29.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBox_29.setFrame(True)
        self.spinBox_29.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_29.setMaximum(999)
        self.spinBox_29.setObjectName(_fromUtf8("spinBox_29"))
        self.horizontalLayout_24.addWidget(self.spinBox_29)
        self.spinBox_28 = QtGui.QSpinBox(self.Left)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_28.sizePolicy().hasHeightForWidth())
        self.spinBox_28.setSizePolicy(sizePolicy)
        self.spinBox_28.setMinimumSize(QtCore.QSize(80, 0))
        self.spinBox_28.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBox_28.setFrame(True)
        self.spinBox_28.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_28.setMaximum(999)
        self.spinBox_28.setObjectName(_fromUtf8("spinBox_28"))
        self.horizontalLayout_24.addWidget(self.spinBox_28)
        self.verticalLayout_9.addWidget(self.Left)
        self.Leftup = QtGui.QWidget(self.EntityAnimationBox)
        self.Leftup.setObjectName(_fromUtf8("Leftup"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout(self.Leftup)
        self.horizontalLayout_26.setMargin(0)
        self.horizontalLayout_26.setMargin(0)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_19 = QtGui.QLabel(self.Leftup)
        self.label_19.setText(QtGui.QApplication.translate("Editor", "Left-Up:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_26.addWidget(self.label_19)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem19)
        self.spinBox_31 = QtGui.QSpinBox(self.Leftup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_31.sizePolicy().hasHeightForWidth())
        self.spinBox_31.setSizePolicy(sizePolicy)
        self.spinBox_31.setMinimumSize(QtCore.QSize(80, 0))
        self.spinBox_31.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBox_31.setFrame(True)
        self.spinBox_31.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_31.setMaximum(999)
        self.spinBox_31.setObjectName(_fromUtf8("spinBox_31"))
        self.horizontalLayout_26.addWidget(self.spinBox_31)
        self.spinBox_30 = QtGui.QSpinBox(self.Leftup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_30.sizePolicy().hasHeightForWidth())
        self.spinBox_30.setSizePolicy(sizePolicy)
        self.spinBox_30.setMinimumSize(QtCore.QSize(80, 0))
        self.spinBox_30.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBox_30.setFrame(True)
        self.spinBox_30.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_30.setMaximum(999)
        self.spinBox_30.setObjectName(_fromUtf8("spinBox_30"))
        self.horizontalLayout_26.addWidget(self.spinBox_30)
        self.verticalLayout_9.addWidget(self.Leftup)
        self.verticalLayout_14.addWidget(self.EntityAnimationBox)
        self.EntityAnimaptionPreview = QtGui.QGroupBox(self.EntityTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EntityAnimaptionPreview.sizePolicy().hasHeightForWidth())
        self.EntityAnimaptionPreview.setSizePolicy(sizePolicy)
        self.EntityAnimaptionPreview.setTitle(QtGui.QApplication.translate("Editor", "Animation preview", None, QtGui.QApplication.UnicodeUTF8))
        self.EntityAnimaptionPreview.setObjectName(_fromUtf8("EntityAnimaptionPreview"))
        self.gridLayout_2 = QtGui.QGridLayout(self.EntityAnimaptionPreview)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.EntityAnimationSettings = QtGui.QWidget(self.EntityAnimaptionPreview)
        self.EntityAnimationSettings.setObjectName(_fromUtf8("EntityAnimationSettings"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.EntityAnimationSettings)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.EntityAnimationChooser = QtGui.QComboBox(self.EntityAnimationSettings)
        self.EntityAnimationChooser.setObjectName(_fromUtf8("EntityAnimationChooser"))
        self.verticalLayout_5.addWidget(self.EntityAnimationChooser)
        self.EntityAnimationFrame = QtGui.QWidget(self.EntityAnimationSettings)
        self.EntityAnimationFrame.setEnabled(True)
        self.EntityAnimationFrame.setObjectName(_fromUtf8("EntityAnimationFrame"))
        self.width_5 = QtGui.QHBoxLayout(self.EntityAnimationFrame)
        self.width_5.setMargin(0)
        self.width_5.setMargin(0)
        self.width_5.setObjectName(_fromUtf8("width_5"))
        self.horizontalScrollBar_2 = QtGui.QScrollBar(self.EntityAnimationFrame)
        self.horizontalScrollBar_2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalScrollBar_2.sizePolicy().hasHeightForWidth())
        self.horizontalScrollBar_2.setSizePolicy(sizePolicy)
        self.horizontalScrollBar_2.setMinimum(1)
        self.horizontalScrollBar_2.setMaximum(99)
        self.horizontalScrollBar_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_2.setInvertedAppearance(False)
        self.horizontalScrollBar_2.setObjectName(_fromUtf8("horizontalScrollBar_2"))
        self.width_5.addWidget(self.horizontalScrollBar_2)
        self.spinBox_4 = QtGui.QSpinBox(self.EntityAnimationFrame)
        self.spinBox_4.setMaximumSize(QtCore.QSize(30, 16777215))
        self.spinBox_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_4.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_4.setMinimum(1)
        self.spinBox_4.setMaximum(99)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.width_5.addWidget(self.spinBox_4)
        self.verticalLayout_5.addWidget(self.EntityAnimationFrame)
        self.EntityAnimationDelay = QtGui.QWidget(self.EntityAnimationSettings)
        self.EntityAnimationDelay.setObjectName(_fromUtf8("EntityAnimationDelay"))
        self.imgrows_3 = QtGui.QHBoxLayout(self.EntityAnimationDelay)
        self.imgrows_3.setMargin(0)
        self.imgrows_3.setMargin(0)
        self.imgrows_3.setObjectName(_fromUtf8("imgrows_3"))
        self.label_33 = QtGui.QLabel(self.EntityAnimationDelay)
        self.label_33.setText(QtGui.QApplication.translate("Editor", "Delay:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.imgrows_3.addWidget(self.label_33)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.imgrows_3.addItem(spacerItem20)
        self.DelaySpin = QtGui.QSpinBox(self.EntityAnimationDelay)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DelaySpin.sizePolicy().hasHeightForWidth())
        self.DelaySpin.setSizePolicy(sizePolicy)
        self.DelaySpin.setMinimumSize(QtCore.QSize(0, 0))
        self.DelaySpin.setSizeIncrement(QtCore.QSize(0, 0))
        self.DelaySpin.setBaseSize(QtCore.QSize(0, 0))
        self.DelaySpin.setMouseTracking(False)
        self.DelaySpin.setAcceptDrops(False)
        self.DelaySpin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DelaySpin.setAutoFillBackground(False)
        self.DelaySpin.setWrapping(False)
        self.DelaySpin.setFrame(True)
        self.DelaySpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DelaySpin.setKeyboardTracking(True)
        self.DelaySpin.setMinimum(1)
        self.DelaySpin.setMaximum(999999999)
        self.DelaySpin.setObjectName(_fromUtf8("DelaySpin"))
        self.imgrows_3.addWidget(self.DelaySpin)
        self.verticalLayout_5.addWidget(self.EntityAnimationDelay)
        self.EntityAnimationPlay = QtGui.QPushButton(self.EntityAnimationSettings)
        self.EntityAnimationPlay.setText(QtGui.QApplication.translate("Editor", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.EntityAnimationPlay.setAutoDefault(False)
        self.EntityAnimationPlay.setDefault(False)
        self.EntityAnimationPlay.setFlat(False)
        self.EntityAnimationPlay.setObjectName(_fromUtf8("EntityAnimationPlay"))
        self.verticalLayout_5.addWidget(self.EntityAnimationPlay)
        self.gridLayout_2.addWidget(self.EntityAnimationSettings, 0, 2, 1, 1)
        self.EntityAnimationViewer = QtGui.QLabel(self.EntityAnimaptionPreview)
        self.EntityAnimationViewer.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.EntityAnimationViewer.sizePolicy().hasHeightForWidth())
        self.EntityAnimationViewer.setSizePolicy(sizePolicy)
        self.EntityAnimationViewer.setMinimumSize(QtCore.QSize(64, 64))
        self.EntityAnimationViewer.setMaximumSize(QtCore.QSize(200, 200))
        self.EntityAnimationViewer.setSizeIncrement(QtCore.QSize(0, 0))
        self.EntityAnimationViewer.setStyleSheet(_fromUtf8("QLabel {\n"
"    padding: 1px;\n"
"}"))
        self.EntityAnimationViewer.setFrameShape(QtGui.QFrame.Box)
        self.EntityAnimationViewer.setFrameShadow(QtGui.QFrame.Sunken)
        self.EntityAnimationViewer.setLineWidth(1)
        self.EntityAnimationViewer.setMidLineWidth(0)
        self.EntityAnimationViewer.setText(_fromUtf8(""))
        self.EntityAnimationViewer.setTextFormat(QtCore.Qt.AutoText)
        self.EntityAnimationViewer.setScaledContents(False)
        self.EntityAnimationViewer.setAlignment(QtCore.Qt.AlignCenter)
        self.EntityAnimationViewer.setWordWrap(False)
        self.EntityAnimationViewer.setIndent(0)
        self.EntityAnimationViewer.setOpenExternalLinks(False)
        self.EntityAnimationViewer.setObjectName(_fromUtf8("EntityAnimationViewer"))
        self.gridLayout_2.addWidget(self.EntityAnimationViewer, 0, 0, 1, 1)
        spacerItem21 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem21, 0, 1, 1, 1)
        self.verticalLayout_14.addWidget(self.EntityAnimaptionPreview)
        spacerItem22 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem22)
        self.horizontalLayout_4.addLayout(self.verticalLayout_14)
        self.MainTabs.addTab(self.EntityTab, _fromUtf8(""))
        self.WidgetsTab = QtGui.QWidget()
        self.WidgetsTab.setObjectName(_fromUtf8("WidgetsTab"))
        self.MainTabs.addTab(self.WidgetsTab, _fromUtf8(""))
        self.MapTilesTab = QtGui.QWidget()
        self.MapTilesTab.setObjectName(_fromUtf8("MapTilesTab"))
        self.formLayout_2 = QtGui.QFormLayout(self.MapTilesTab)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.TilesMainBox = QtGui.QGroupBox(self.MapTilesTab)
        self.TilesMainBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.TilesMainBox.setTitle(QtGui.QApplication.translate("Editor", "Main", None, QtGui.QApplication.UnicodeUTF8))
        self.TilesMainBox.setObjectName(_fromUtf8("TilesMainBox"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.TilesMainBox)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.ID_4 = QtGui.QWidget(self.TilesMainBox)
        self.ID_4.setEnabled(True)
        self.ID_4.setObjectName(_fromUtf8("ID_4"))
        self.meeting_11 = QtGui.QHBoxLayout(self.ID_4)
        self.meeting_11.setMargin(0)
        self.meeting_11.setMargin(0)
        self.meeting_11.setObjectName(_fromUtf8("meeting_11"))
        self.label_85 = QtGui.QLabel(self.ID_4)
        self.label_85.setText(QtGui.QApplication.translate("Editor", "ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.meeting_11.addWidget(self.label_85)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.meeting_11.addItem(spacerItem23)
        self.spinBox = QtGui.QSpinBox(self.ID_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setMinimumSize(QtCore.QSize(190, 0))
        self.spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox.setReadOnly(True)
        self.spinBox.setMaximum(999999999)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.meeting_11.addWidget(self.spinBox)
        self.verticalLayout_15.addWidget(self.ID_4)
        self.Name_2 = YSimpleInputWidget(self.TilesMainBox)
        self.Name_2.setObjectName(_fromUtf8("Name_2"))
        self.verticalLayout_15.addWidget(self.Name_2)
        self.Image_4 = QtGui.QWidget(self.TilesMainBox)
        self.Image_4.setObjectName(_fromUtf8("Image_4"))
        self.Image_10 = QtGui.QHBoxLayout(self.Image_4)
        self.Image_10.setMargin(0)
        self.Image_10.setMargin(0)
        self.Image_10.setObjectName(_fromUtf8("Image_10"))
        self.label_5 = QtGui.QLabel(self.Image_4)
        self.label_5.setText(QtGui.QApplication.translate("Editor", "Image:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.Image_10.addWidget(self.label_5)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Image_10.addItem(spacerItem24)
        self.EntityImgField_3 = QtGui.QLineEdit(self.Image_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EntityImgField_3.sizePolicy().hasHeightForWidth())
        self.EntityImgField_3.setSizePolicy(sizePolicy)
        self.EntityImgField_3.setMinimumSize(QtCore.QSize(0, 0))
        self.EntityImgField_3.setMaximumSize(QtCore.QSize(110, 16777215))
        self.EntityImgField_3.setObjectName(_fromUtf8("EntityImgField_3"))
        self.Image_10.addWidget(self.EntityImgField_3)
        self.ImageChooseButton = QtGui.QPushButton(self.Image_4)
        self.ImageChooseButton.setText(QtGui.QApplication.translate("Editor", "Choose", None, QtGui.QApplication.UnicodeUTF8))
        self.ImageChooseButton.setAutoDefault(False)
        self.ImageChooseButton.setDefault(False)
        self.ImageChooseButton.setFlat(False)
        self.ImageChooseButton.setObjectName(_fromUtf8("ImageChooseButton"))
        self.Image_10.addWidget(self.ImageChooseButton)
        self.verticalLayout_15.addWidget(self.Image_4)
        self.OffsetX = QtGui.QWidget(self.TilesMainBox)
        self.OffsetX.setObjectName(_fromUtf8("OffsetX"))
        self.imgrows_2 = QtGui.QHBoxLayout(self.OffsetX)
        self.imgrows_2.setMargin(0)
        self.imgrows_2.setMargin(0)
        self.imgrows_2.setObjectName(_fromUtf8("imgrows_2"))
        self.label_25 = QtGui.QLabel(self.OffsetX)
        self.label_25.setText(QtGui.QApplication.translate("Editor", "Offset X:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.imgrows_2.addWidget(self.label_25)
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.imgrows_2.addItem(spacerItem25)
        self.TilesOffestXSpin = QtGui.QSpinBox(self.OffsetX)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TilesOffestXSpin.sizePolicy().hasHeightForWidth())
        self.TilesOffestXSpin.setSizePolicy(sizePolicy)
        self.TilesOffestXSpin.setMinimumSize(QtCore.QSize(120, 0))
        self.TilesOffestXSpin.setSizeIncrement(QtCore.QSize(0, 0))
        self.TilesOffestXSpin.setBaseSize(QtCore.QSize(0, 0))
        self.TilesOffestXSpin.setMouseTracking(False)
        self.TilesOffestXSpin.setAcceptDrops(False)
        self.TilesOffestXSpin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TilesOffestXSpin.setAutoFillBackground(False)
        self.TilesOffestXSpin.setWrapping(False)
        self.TilesOffestXSpin.setFrame(True)
        self.TilesOffestXSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TilesOffestXSpin.setKeyboardTracking(True)
        self.TilesOffestXSpin.setMaximum(999999999)
        self.TilesOffestXSpin.setObjectName(_fromUtf8("TilesOffestXSpin"))
        self.imgrows_2.addWidget(self.TilesOffestXSpin)
        self.Multipler_21 = QtGui.QWidget(self.OffsetX)
        self.Multipler_21.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Multipler_21.setObjectName(_fromUtf8("Multipler_21"))
        self.horizontalLayout_69 = QtGui.QHBoxLayout(self.Multipler_21)
        self.horizontalLayout_69.setMargin(0)
        self.horizontalLayout_69.setMargin(0)
        self.horizontalLayout_69.setObjectName(_fromUtf8("horizontalLayout_69"))
        self.label_122 = QtGui.QLabel(self.Multipler_21)
        self.label_122.setText(QtGui.QApplication.translate("Editor", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_122.setObjectName(_fromUtf8("label_122"))
        self.horizontalLayout_69.addWidget(self.label_122)
        self.spinBox_96 = QtGui.QSpinBox(self.Multipler_21)
        self.spinBox_96.setMaximumSize(QtCore.QSize(48, 16777215))
        self.spinBox_96.setMinimum(1)
        self.spinBox_96.setMaximum(999)
        self.spinBox_96.setObjectName(_fromUtf8("spinBox_96"))
        self.horizontalLayout_69.addWidget(self.spinBox_96)
        self.imgrows_2.addWidget(self.Multipler_21)
        self.verticalLayout_15.addWidget(self.OffsetX)
        self.OffsetY = QtGui.QWidget(self.TilesMainBox)
        self.OffsetY.setObjectName(_fromUtf8("OffsetY"))
        self.height_2 = QtGui.QHBoxLayout(self.OffsetY)
        self.height_2.setMargin(0)
        self.height_2.setMargin(0)
        self.height_2.setObjectName(_fromUtf8("height_2"))
        self.label_26 = QtGui.QLabel(self.OffsetY)
        self.label_26.setText(QtGui.QApplication.translate("Editor", "Offset Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.height_2.addWidget(self.label_26)
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.height_2.addItem(spacerItem26)
        self.TilesOffestYSpin = QtGui.QSpinBox(self.OffsetY)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TilesOffestYSpin.sizePolicy().hasHeightForWidth())
        self.TilesOffestYSpin.setSizePolicy(sizePolicy)
        self.TilesOffestYSpin.setMinimumSize(QtCore.QSize(120, 0))
        self.TilesOffestYSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TilesOffestYSpin.setAccelerated(False)
        self.TilesOffestYSpin.setMaximum(999999999)
        self.TilesOffestYSpin.setObjectName(_fromUtf8("TilesOffestYSpin"))
        self.height_2.addWidget(self.TilesOffestYSpin)
        self.Multipler_22 = QtGui.QWidget(self.OffsetY)
        self.Multipler_22.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Multipler_22.setObjectName(_fromUtf8("Multipler_22"))
        self.horizontalLayout_70 = QtGui.QHBoxLayout(self.Multipler_22)
        self.horizontalLayout_70.setMargin(0)
        self.horizontalLayout_70.setMargin(0)
        self.horizontalLayout_70.setObjectName(_fromUtf8("horizontalLayout_70"))
        self.label_123 = QtGui.QLabel(self.Multipler_22)
        self.label_123.setText(QtGui.QApplication.translate("Editor", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_123.setObjectName(_fromUtf8("label_123"))
        self.horizontalLayout_70.addWidget(self.label_123)
        self.spinBox_97 = QtGui.QSpinBox(self.Multipler_22)
        self.spinBox_97.setMaximumSize(QtCore.QSize(48, 16777215))
        self.spinBox_97.setMinimum(1)
        self.spinBox_97.setMaximum(999)
        self.spinBox_97.setObjectName(_fromUtf8("spinBox_97"))
        self.horizontalLayout_70.addWidget(self.spinBox_97)
        self.height_2.addWidget(self.Multipler_22)
        self.verticalLayout_15.addWidget(self.OffsetY)
        self.Passability = QtGui.QWidget(self.TilesMainBox)
        self.Passability.setObjectName(_fromUtf8("Passability"))
        self.height_3 = QtGui.QHBoxLayout(self.Passability)
        self.height_3.setMargin(0)
        self.height_3.setMargin(0)
        self.height_3.setObjectName(_fromUtf8("height_3"))
        self.label_29 = QtGui.QLabel(self.Passability)
        self.label_29.setText(QtGui.QApplication.translate("Editor", "Passability:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.height_3.addWidget(self.label_29)
        spacerItem27 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.height_3.addItem(spacerItem27)
        self.TilesOffestYSpin_2 = QtGui.QDoubleSpinBox(self.Passability)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TilesOffestYSpin_2.sizePolicy().hasHeightForWidth())
        self.TilesOffestYSpin_2.setSizePolicy(sizePolicy)
        self.TilesOffestYSpin_2.setMinimumSize(QtCore.QSize(120, 0))
        self.TilesOffestYSpin_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TilesOffestYSpin_2.setAccelerated(False)
        self.TilesOffestYSpin_2.setMaximum(1.0)
        self.TilesOffestYSpin_2.setSingleStep(0.1)
        self.TilesOffestYSpin_2.setProperty("value", 1.0)
        self.TilesOffestYSpin_2.setObjectName(_fromUtf8("TilesOffestYSpin_2"))
        self.height_3.addWidget(self.TilesOffestYSpin_2)
        self.Multipler_23 = QtGui.QWidget(self.Passability)
        self.Multipler_23.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Multipler_23.setObjectName(_fromUtf8("Multipler_23"))
        self.horizontalLayout_71 = QtGui.QHBoxLayout(self.Multipler_23)
        self.horizontalLayout_71.setMargin(0)
        self.horizontalLayout_71.setMargin(0)
        self.horizontalLayout_71.setObjectName(_fromUtf8("horizontalLayout_71"))
        self.label_124 = QtGui.QLabel(self.Multipler_23)
        self.label_124.setText(QtGui.QApplication.translate("Editor", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_124.setObjectName(_fromUtf8("label_124"))
        self.horizontalLayout_71.addWidget(self.label_124)
        self.spinBox_98 = QtGui.QSpinBox(self.Multipler_23)
        self.spinBox_98.setMaximumSize(QtCore.QSize(48, 16777215))
        self.spinBox_98.setMinimum(1)
        self.spinBox_98.setMaximum(999)
        self.spinBox_98.setObjectName(_fromUtf8("spinBox_98"))
        self.horizontalLayout_71.addWidget(self.spinBox_98)
        self.height_3.addWidget(self.Multipler_23)
        self.verticalLayout_15.addWidget(self.Passability)
        self.Backing = QtGui.QWidget(self.TilesMainBox)
        self.Backing.setObjectName(_fromUtf8("Backing"))
        self.width_2 = QtGui.QHBoxLayout(self.Backing)
        self.width_2.setMargin(0)
        self.width_2.setMargin(0)
        self.width_2.setObjectName(_fromUtf8("width_2"))
        self.label_27 = QtGui.QLabel(self.Backing)
        self.label_27.setText(QtGui.QApplication.translate("Editor", "Backing:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.width_2.addWidget(self.label_27)
        spacerItem28 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.width_2.addItem(spacerItem28)
        self.checkBox = QtGui.QCheckBox(self.Backing)
        self.checkBox.setText(_fromUtf8(""))
        self.checkBox.setChecked(False)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.width_2.addWidget(self.checkBox)
        self.verticalLayout_15.addWidget(self.Backing)
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.TilesMainBox)
        self.groupBox_8 = QtGui.QGroupBox(self.MapTilesTab)
        self.groupBox_8.setTitle(QtGui.QApplication.translate("Editor", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.TileImageViewer = QtGui.QLabel(self.groupBox_8)
        self.TileImageViewer.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TileImageViewer.sizePolicy().hasHeightForWidth())
        self.TileImageViewer.setSizePolicy(sizePolicy)
        self.TileImageViewer.setMinimumSize(QtCore.QSize(64, 64))
        self.TileImageViewer.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.TileImageViewer.setSizeIncrement(QtCore.QSize(0, 0))
        self.TileImageViewer.setStyleSheet(_fromUtf8("QLabel {\n"
"    padding: 1px;\n"
"}"))
        self.TileImageViewer.setFrameShape(QtGui.QFrame.Box)
        self.TileImageViewer.setFrameShadow(QtGui.QFrame.Sunken)
        self.TileImageViewer.setLineWidth(1)
        self.TileImageViewer.setMidLineWidth(0)
        self.TileImageViewer.setText(_fromUtf8(""))
        self.TileImageViewer.setTextFormat(QtCore.Qt.AutoText)
        self.TileImageViewer.setScaledContents(False)
        self.TileImageViewer.setAlignment(QtCore.Qt.AlignCenter)
        self.TileImageViewer.setWordWrap(False)
        self.TileImageViewer.setIndent(0)
        self.TileImageViewer.setOpenExternalLinks(False)
        self.TileImageViewer.setObjectName(_fromUtf8("TileImageViewer"))
        self.horizontalLayout_6.addWidget(self.TileImageViewer)
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.groupBox_8)
        self.MainTabs.addTab(self.MapTilesTab, _fromUtf8(""))
        self.MapTab = QtGui.QWidget()
        self.MapTab.setAutoFillBackground(False)
        self.MapTab.setObjectName(_fromUtf8("MapTab"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.MapTab)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.MapElements = QtGui.QToolBox(self.MapTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MapElements.sizePolicy().hasHeightForWidth())
        self.MapElements.setSizePolicy(sizePolicy)
        self.MapElements.setMinimumSize(QtCore.QSize(280, 0))
        self.MapElements.setMaximumSize(QtCore.QSize(280, 16777215))
        self.MapElements.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MapElements.setAutoFillBackground(False)
        self.MapElements.setStyleSheet(_fromUtf8("#MapElements::tab:selected { font: bold; height: 26px;} /* selected tab */\n"
"#MapElements::tab:!selected { height: 26px;} /* non-selected tab */\n"
"#MapElements{\n"
"border: 0px transparent;\n"
"}"))
        self.MapElements.setFrameShape(QtGui.QFrame.NoFrame)
        self.MapElements.setObjectName(_fromUtf8("MapElements"))
        self.MapTilesPage = QtGui.QWidget()
        self.MapTilesPage.setGeometry(QtCore.QRect(0, 0, 280, 517))
        self.MapTilesPage.setObjectName(_fromUtf8("MapTilesPage"))
        self.gridLayout = QtGui.QGridLayout(self.MapTilesPage)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.MapElements.addItem(self.MapTilesPage, _fromUtf8(""))
        self.MapObjectsPage = QtGui.QWidget()
        self.MapObjectsPage.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.MapObjectsPage.setObjectName(_fromUtf8("MapObjectsPage"))
        self.MapElements.addItem(self.MapObjectsPage, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.MapElements)
        self.verticalWidget = QtGui.QWidget(self.MapTab)
        self.verticalWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalWidget.setObjectName(_fromUtf8("verticalWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.MapAdditionalBox = QtGui.QGroupBox(self.verticalWidget)
        self.MapAdditionalBox.setTitle(QtGui.QApplication.translate("Editor", "Additional", None, QtGui.QApplication.UnicodeUTF8))
        self.MapAdditionalBox.setCheckable(False)
        self.MapAdditionalBox.setObjectName(_fromUtf8("MapAdditionalBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.MapAdditionalBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.MapErase = QtGui.QPushButton(self.MapAdditionalBox)
        self.MapErase.setText(QtGui.QApplication.translate("Editor", "Erase", None, QtGui.QApplication.UnicodeUTF8))
        self.MapErase.setCheckable(True)
        self.MapErase.setChecked(False)
        self.MapErase.setAutoDefault(False)
        self.MapErase.setDefault(False)
        self.MapErase.setFlat(False)
        self.MapErase.setObjectName(_fromUtf8("MapErase"))
        self.verticalLayout_3.addWidget(self.MapErase)
        self.verticalLayout_2.addWidget(self.MapAdditionalBox)
        self.MapOptionsBox = QtGui.QGroupBox(self.verticalWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MapOptionsBox.sizePolicy().hasHeightForWidth())
        self.MapOptionsBox.setSizePolicy(sizePolicy)
        self.MapOptionsBox.setMinimumSize(QtCore.QSize(100, 480))
        self.MapOptionsBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MapOptionsBox.setAutoFillBackground(False)
        self.MapOptionsBox.setTitle(QtGui.QApplication.translate("Editor", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.MapOptionsBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.MapOptionsBox.setFlat(False)
        self.MapOptionsBox.setCheckable(False)
        self.MapOptionsBox.setObjectName(_fromUtf8("MapOptionsBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.MapOptionsBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.ID_5 = YReadOnlySimpleInputWidget(self.MapOptionsBox)
        self.ID_5.setEnabled(True)
        self.ID_5.setObjectName(_fromUtf8("ID_5"))
        self.verticalLayout.addWidget(self.ID_5)
        self.RegionName = QtGui.QWidget(self.MapOptionsBox)
        self.RegionName.setEnabled(True)
        self.RegionName.setObjectName(_fromUtf8("RegionName"))
        self.meeting_3 = QtGui.QHBoxLayout(self.RegionName)
        self.meeting_3.setMargin(0)
        self.meeting_3.setMargin(0)
        self.meeting_3.setObjectName(_fromUtf8("meeting_3"))
        self.label_20 = QtGui.QLabel(self.RegionName)
        self.label_20.setText(QtGui.QApplication.translate("Editor", "Region name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.meeting_3.addWidget(self.label_20)
        spacerItem29 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.meeting_3.addItem(spacerItem29)
        self.lineEdit_22 = QtGui.QLineEdit(self.RegionName)
        self.lineEdit_22.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_22.setMaximumSize(QtCore.QSize(190, 16777215))
        self.lineEdit_22.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.meeting_3.addWidget(self.lineEdit_22)
        self.verticalLayout.addWidget(self.RegionName)
        self.MapBack = QtGui.QWidget(self.MapOptionsBox)
        self.MapBack.setObjectName(_fromUtf8("MapBack"))
        self.width_3 = QtGui.QHBoxLayout(self.MapBack)
        self.width_3.setMargin(0)
        self.width_3.setMargin(0)
        self.width_3.setObjectName(_fromUtf8("width_3"))
        self.label_30 = QtGui.QLabel(self.MapBack)
        self.label_30.setText(QtGui.QApplication.translate("Editor", "Backing:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.width_3.addWidget(self.label_30)
        spacerItem30 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.width_3.addItem(spacerItem30)
        self.checkBox_2 = QtGui.QCheckBox(self.MapBack)
        self.checkBox_2.setText(_fromUtf8(""))
        self.checkBox_2.setChecked(False)
        self.checkBox_2.setTristate(False)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.width_3.addWidget(self.checkBox_2)
        self.verticalLayout.addWidget(self.MapBack)
        self.BrushSize = QtGui.QWidget(self.MapOptionsBox)
        self.BrushSize.setEnabled(False)
        self.BrushSize.setObjectName(_fromUtf8("BrushSize"))
        self.width_4 = QtGui.QHBoxLayout(self.BrushSize)
        self.width_4.setMargin(0)
        self.width_4.setMargin(0)
        self.width_4.setObjectName(_fromUtf8("width_4"))
        self.label_31 = QtGui.QLabel(self.BrushSize)
        self.label_31.setText(QtGui.QApplication.translate("Editor", "Brush size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.width_4.addWidget(self.label_31)
        self.horizontalScrollBar = QtGui.QScrollBar(self.BrushSize)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalScrollBar.sizePolicy().hasHeightForWidth())
        self.horizontalScrollBar.setSizePolicy(sizePolicy)
        self.horizontalScrollBar.setMinimum(1)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName(_fromUtf8("horizontalScrollBar"))
        self.width_4.addWidget(self.horizontalScrollBar)
        self.spinBox_2 = QtGui.QSpinBox(self.BrushSize)
        self.spinBox_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.spinBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(99)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.width_4.addWidget(self.spinBox_2)
        self.verticalLayout.addWidget(self.BrushSize)
        spacerItem31 = QtGui.QSpacerItem(20, 416, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem31)
        self.verticalLayout_2.addWidget(self.MapOptionsBox)
        self.horizontalLayout.addWidget(self.verticalWidget)
        spacerItem32 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem32)
        self.MainTabs.addTab(self.MapTab, _fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.MainTabs)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addWidget(self.widget)
        self.folder = QtGui.QHBoxLayout()
        self.folder.setObjectName(_fromUtf8("folder"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setText(QtGui.QApplication.translate("Editor", "Source files directory path:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.folder.addWidget(self.label)
        self.FolderPlace = QtGui.QLineEdit(self.centralwidget)
        self.FolderPlace.setReadOnly(True)
        self.FolderPlace.setObjectName(_fromUtf8("FolderPlace"))
        self.folder.addWidget(self.FolderPlace)
        self.OpenFolderDBox = QtGui.QDialogButtonBox(self.centralwidget)
        self.OpenFolderDBox.setMaximumSize(QtCore.QSize(75, 16777215))
        self.OpenFolderDBox.setOrientation(QtCore.Qt.Horizontal)
        self.OpenFolderDBox.setStandardButtons(QtGui.QDialogButtonBox.Open)
        self.OpenFolderDBox.setCenterButtons(False)
        self.OpenFolderDBox.setObjectName(_fromUtf8("OpenFolderDBox"))
        self.folder.addWidget(self.OpenFolderDBox)
        self.verticalLayout_4.addLayout(self.folder)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.exitbox = QtGui.QDialogButtonBox(self.centralwidget)
        self.exitbox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.RestoreDefaults|QtGui.QDialogButtonBox.Save)
        self.exitbox.setCenterButtons(False)
        self.exitbox.setObjectName(_fromUtf8("exitbox"))
        self.horizontalLayout_2.addWidget(self.exitbox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        Editor.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Editor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 821, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        Editor.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Editor)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Editor.setStatusBar(self.statusbar)

        self.retranslateUi(Editor)
        self.MainTabs.setCurrentIndex(0)
        self.MapElements.setCurrentIndex(0)
        QtCore.QObject.connect(self.horizontalScrollBar, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_2.setValue)
        QtCore.QObject.connect(self.spinBox_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalScrollBar.setValue)
        QtCore.QObject.connect(self.horizontalScrollBar_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_4.setValue)
        QtCore.QObject.connect(self.spinBox_4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalScrollBar_2.setValue)
        QtCore.QMetaObject.connectSlotsByName(Editor)
        Editor.setTabOrder(self.FolderPlace, self.exitbox)

    def retranslateUi(self, Editor):
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.SpriteTab), QtGui.QApplication.translate("Editor", "Sprites", None, QtGui.QApplication.UnicodeUTF8))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.EntityTab), QtGui.QApplication.translate("Editor", "Entity", None, QtGui.QApplication.UnicodeUTF8))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.WidgetsTab), QtGui.QApplication.translate("Editor", "Widgets", None, QtGui.QApplication.UnicodeUTF8))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.MapTilesTab), QtGui.QApplication.translate("Editor", "Tiles", None, QtGui.QApplication.UnicodeUTF8))
        self.MapElements.setItemText(self.MapElements.indexOf(self.MapTilesPage), QtGui.QApplication.translate("Editor", "Tiles", None, QtGui.QApplication.UnicodeUTF8))
        self.MapElements.setItemText(self.MapElements.indexOf(self.MapObjectsPage), QtGui.QApplication.translate("Editor", "Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.MapTab), QtGui.QApplication.translate("Editor", "Map", None, QtGui.QApplication.UnicodeUTF8))

from widgets import YReadOnlySimpleInputWidget, YSpinBoxInputWidget, YSimpleInputWidget
