/*
 * Constants.h
 *
 *  Created on: 03.04.2013
 */

#ifndef MAP_CONSTANTS_H_
#define MAP_CONSTANTS_H_

#define REGION_CHUNK_SIZE 16

enum Biomes
{
	bNONE = 0, bOCEAN, bLAKE, bBEACH, bMARSH, bICE, bSNOW, bTUNDRA, bBARE,
	bSCORCHED, bTAIGA, bSHRUBLAND, bTEMPERATE_DESERT, bTEMPERATE_RAIN_FOREST,
	bTEMPERATE_DECIDUOUS_FOREST, bGRASSLAND, bTROPICAL_RAIN_FOREST,
	bTROPICAL_SEASONAL_FOREST, bSUBTROPICAL_DESERT, bLAST
};

typedef enum Biomes Biome;



#endif /* MAP_CONSTANTS_H_ */
